# -*- coding: utf-8 -*-
"""Dra-och-släpp-övningar (sortering) för Separationsprocesser."""

def act(id, tier, title, intro, zones, items):
    """zones: [(id, text)], items: [(zone, text, why[, hint])]"""
    out = {"id": id, "tier": tier, "title": title, "intro": intro,
           "zones": [{"id": z, "t": t} for z, t in zones], "items": []}
    for i, it in enumerate(items, 1):
        d = {"id": str(i), "zone": it[0], "t": it[1], "why": it[2]}
        if len(it) > 3: d["hint"] = it[3]
        out["items"].append(d)
    return out

SORTERING = [
 act("former", "Grund", "Fast form, flytande form eller gas?",
     "Vilken form beskriver varje bricka? Tänk på hur partiklarna sitter och rör sig.",
     [("s", "Fast form"), ("l", "Flytande form"), ("g", "Gas")],
     [("s", "Partiklarna sitter på bestämda platser", "I fast form vibrerar partiklarna men byter inte plats."),
      ("s", "Har egen form och egen volym", "Fasta ämnen behåller sin form."),
      ("s", "En isbit", "Is är vatten i fast form."),
      ("l", "Partiklarna glider förbi varandra men ligger tätt", "Det är kännetecknet för en vätska."),
      ("l", "Tar formen av kärlet men har egen volym", "En vätska fyller inte hela kärlet, bara så mycket som volymen räcker till."),
      ("l", "Vatten från kranen", "Vatten är flytande vid rumstemperatur."),
      ("g", "Partiklarna far runt med stora avstånd", "I en gas är det långt mellan partiklarna."),
      ("g", "Kan pressas ihop lätt", "Det är mycket tomrum mellan partiklarna i en gas."),
      ("g", "Fyller hela utrymmet den är i", "En gas sprider ut sig så att den fyller kärlet."),
      ("g", "Vattenånga", "Vattenånga är vatten i gasform.")]),

 act("fasovergangar", "Grund", "Vilken fasövergång är det?",
     "Sortera händelserna efter vad som sker med ämnet.",
     [("sm", "Smältning"), ("st", "Stelning"), ("ko", "Kokning eller avdunstning"), ("kd", "Kondensering")],
     [("sm", "Isen i glaset blir till vatten", "Fast form blir flytande: smältning."),
      ("sm", "Choklad blir mjuk i handen", "Choklad smälter: fast blir flytande."),
      ("st", "Vattnet i en pöl blir till is en kall natt", "Flytande blir fast: stelning (frysning)."),
      ("st", "Smält vax blir hårt igen", "Flytande vax blir fast: stelning."),
      ("ko", "Vattnet i kastrullen bubblar och blir ånga", "Vätska blir gas i hela vätskan: kokning."),
      ("ko", "Tvätten på tvättlinan torkar", "Vattnet lämnar tyget som gas: avdunstning."),
      ("kd", "Det blir droppar på insidan av ett kallt fönster", "Vattenånga i luften kyls och blir vätska: kondensering."),
      ("kd", "Ångan från duschen blir imma på spegeln", "Gas blir vätska på den kalla ytan: kondensering.")]),

 act("blandningar", "Grund", "Rent ämne eller blandning?",
     "Har ämnet bara en sorts partiklar, eller är det flera ämnen som är blandade?",
     [("r", "Rent ämne"), ("b", "Blandning")],
     [("r", "Syre (O₂)", "Bara en sorts molekyler: ett rent ämne."),
      ("r", "Destillerat vatten", "Vatten som renats från lösta ämnen: ett rent ämne."),
      ("r", "Järn", "Ett grundämne: ett rent ämne."),
      ("r", "Koldioxid (CO₂)", "Bara en sorts molekyler: ett rent ämne."),
      ("r", "Socker", "Ren sackaros består av bara en sorts molekyler."),
      ("b", "Luft", "Mest kväve och syre som är blandade: en blandning."),
      ("b", "Saltvatten", "Salt och vatten som är blandade: en blandning."),
      ("b", "Mjölk", "Vatten, fett, proteiner med mera: en blandning."),
      ("b", "Brons", "Koppar och tenn: en blandning av metaller (legering)."),
      ("b", "Jord", "Många ämnen blandade: en blandning.")]),

 act("blandningstyper", "Grund", "Vilken sorts blandning?",
     "Lösning, slamning, emulsion eller legering? Tänk på vad som är blandat med vad.",
     [("lo", "Lösning"), ("sl", "Slamning"), ("em", "Emulsion"), ("le", "Legering")],
     [("lo", "Salt i vatten", "Saltet är löst och syns inte: en lösning."),
      ("lo", "Socker i te", "Sockret är löst: en lösning."),
      ("sl", "Lera i vatten", "Fasta korn svävar i vätskan och sjunker med tiden: en slamning."),
      ("sl", "Kaffesump i kaffe", "Fasta korn i vätska: en slamning."),
      ("em", "Mjölk", "Små fettdroppar i vatten: en emulsion."),
      ("em", "Majonnäs", "Oljedroppar i vatten stabiliserade av äggula: en emulsion."),
      ("le", "Brons", "Koppar och tenn: en legering."),
      ("le", "Stål", "Järn med lite kol: en legering.")]),

 act("losningsdelar", "Grund", "Lösningsmedel eller löst ämne?",
     "Vad är vattnet och vad är det andra ämnet i varje lösning?",
     [("lm", "Lösningsmedel"), ("ls", "Löst ämne")],
     [("lm", "Vattnet i saltvatten", "Vattnet löser upp saltet."),
      ("lm", "Vattnet i sockerlösning", "Vattnet är det som löser upp."),
      ("lm", "Aceton i nagellacksborttagare", "Acetonet löser upp nagellacket."),
      ("lm", "Vattnet i en kolsyrad dryck", "Vattnet håller koldioxiden löst."),
      ("ls", "Saltet i saltvatten", "Saltet är det som blir upplöst."),
      ("ls", "Sockret i te", "Sockret är det lösta ämnet."),
      ("ls", "Koldioxiden i läsk", "Koldioxiden är lösta gasen."),
      ("ls", "Syret som fiskar andas i vattnet", "Syre är löst i vattnet.")]),

 act("vilkenmetod", "Grund", "Vilken metod passar?",
     "Välj den separationsmetod som passar varje problem bäst.",
     [("si", "Silning eller filtrering"), ("se", "Sedimentering och dekantering"), ("ma", "Magnet"), ("in", "Indunstning"), ("de", "Destillation"), ("kr", "Kromatografi")],
     [("si", "Pasta och kokvatten", "Pastan är stor nog att fastna i silen."),
      ("si", "Kaffesump och kaffe", "Sumpen är olöst och fastnar i filtret."),
      ("se", "Lera som ska sjunka i ett glas vatten", "Leran är tyngre än vattnet och sjunker."),
      ("ma", "Stålburkar bland hushållsavfall", "Stål är magnetiskt."),
      ("ma", "Järnspån i sand", "Bara järnet dras till magneten."),
      ("in", "Salt ur havsvatten (vattnet behövs inte)", "Vattnet dunstar bort och saltet blir kvar."),
      ("de", "Rent vatten ur saltvatten (vattnet ska tas tillvara)", "Vattnet kokar och kondenseras till destillat."),
      ("kr", "Vilka färger finns i en svart tusch?", "Färgämnena vandrar olika långt på pappret.")]),

 act("egenskap", "Lär mer", "Vad skiljer ämnena åt?",
     "Vilken egenskap utnyttjar metoden? Storlek, densitet, magnetism, kokpunkt eller löslighet.",
     [("st", "Storlek"), ("de", "Densitet"), ("ma", "Magnetism"), ("ko", "Kokpunkt"), ("lo", "Löslighet")],
     [("st", "Silen släpper igenom små delar men stoppar stora", "Silning bygger på storleken."),
      ("st", "Filtret stoppar korn men släpper igenom vätska", "Filtrering bygger på storleken."),
      ("de", "Sanden sjunker och vattnet blir klart", "Sedimentering bygger på densitet."),
      ("de", "Grädden samlas när mjölken snurras", "Centrifugering bygger på densitet."),
      ("ma", "Stålskrot plockas ut med en kran med magnet", "Bara magnetiska ämnen dras till magneten."),
      ("ko", "Vattnet ångar bort och saltet blir kvar", "Indunstning bygger på skillnad i kokpunkt."),
      ("ko", "Etanol och vatten skiljs genom att värmas", "Destillation bygger på olika kokpunkter."),
      ("lo", "Smaken lösas ut ur tebladen med varmt vatten", "Extraktion bygger på löslighet."),
      ("lo", "Fosfor fälls ut som flingor i reningsverket", "Fällning bygger på att ämnet blir olösligt.")]),

 act("losning-grad", "Lär mer", "Utspädd, koncentrerad eller mättad?",
     "Beskriv lösningen med rätt ord.",
     [("u", "Utspädd"), ("k", "Koncentrerad"), ("m", "Mättad")],
     [("u", "Bara en nypa salt i en stor kastrull vatten", "Lite löst ämne: utspädd."),
      ("u", "Saft med mycket vatten och lite koncentrat", "Lite löst ämne i mycket lösningsmedel: utspädd."),
      ("k", "Mycket salt i lite vatten, men allt är löst", "Mycket löst ämne: koncentrerad."),
      ("k", "Tjock saftsirap som ännu inte är full", "Mycket löst ämne: koncentrerad."),
      ("m", "Socker ligger kvar på botten hur mycket man än rör", "Mer kan inte lösas: mättad."),
      ("m", "Lösningen kan inte ta upp mer salt vid den temperaturen", "Definitionen av mättad lösning."),
      ("m", "Vid kylning bildas kristaller i den varma lösningen", "Den kalla lösningen kan inte hålla kvar allt: den är mättad.")]),

 act("fysikalisk-kemisk", "Lär mer", "Fysikalisk förändring eller kemisk reaktion?",
     "Vid en kemisk reaktion bildas nya ämnen. Vid en fysikalisk förändring är det samma ämne, bara i ny form eller blandat på nytt sätt. Vilken förändring är varje separationsmetod?",
     [("f", "Fysikalisk förändring"), ("k", "Kemisk reaktion")],
     [("f", "Is smälter", "Samma ämne, bara annan form."),
      ("f", "Saltvatten destilleras", "Vattnet kokar och kondenserar, men det är hela tiden H₂O."),
      ("f", "Sand silas ur vatten", "Inga nya ämnen bildas."),
      ("f", "Socker löses i te", "Sockret finns kvar, bara blandat."),
      ("f", "Vatten indunstas och saltet blir kvar", "Saltet är oförändrat."),
      ("k", "Kalkvatten blir grumligt av koldioxid", "Ett nytt ämne, kalciumkarbonat, bildas."),
      ("k", "Järn rostar", "Järn reagerar med syre och bildar ett nytt ämne."),
      ("k", "Ved brinner", "Nya ämnen, koldioxid och vatten, bildas."),
      ("k", "Fosfor fälls ut med järnsalt", "Ett nytt, olösligt ämne bildas: en fällning.")]),

 act("grundamne-forening", "Lär mer", "Grundämne, kemisk förening eller blandning?",
     "Sortera ämnena. Tänk: bara en sorts atomer, flera sorters atomer som sitter ihop, eller flera ämnen som bara är blandade?",
     [("g", "Grundämne"), ("f", "Kemisk förening"), ("b", "Blandning")],
     [("g", "Järn (Fe)", "Bara järnatomer: ett grundämne."),
      ("g", "Syre (O₂)", "Bara syreatomer: ett grundämne."),
      ("g", "Guld (Au)", "Bara guldatomer: ett grundämne."),
      ("f", "Vatten (H₂O)", "Väte och syre som sitter ihop: en kemisk förening."),
      ("f", "Koldioxid (CO₂)", "Kol och syre som sitter ihop: en förening."),
      ("f", "Koksalt (NaCl)", "Natrium och klor i en förening."),
      ("b", "Luft", "Mest kväve och syre som bara är blandade."),
      ("b", "Saltvatten", "Salt och vatten som är blandade."),
      ("b", "Brons", "Koppar och tenn som är blandade: en legering.")]),

 act("reningsverk", "Lär mer", "Vad händer i vilket steg på reningsverket?",
     "Koppla ihop varje händelse med rätt steg i reningsverket.",
     [("ga", "Rensgaller"), ("sa", "Sandfång och sedimentering"), ("bi", "Biologisk rening"), ("fa", "Kemisk fällning")],
     [("ga", "Stora föremål fastnar i gallret", "Gallret skiljer på storlek."),
      ("ga", "Trasor och skräp tas bort", "Stora delar fångas av gallret."),
      ("sa", "Sand och grus sjunker till botten", "Sandfånget utnyttjar densitet."),
      ("sa", "Slam sjunker i stora bassänger", "Sedimentering: tyngre delar sjunker."),
      ("bi", "Bakterier bryter ned lösta ämnen", "Biologisk rening: mikroorganismer omvandlar lösta ämnen."),
      ("bi", "Kväve omvandlas till kvävgas", "Bakterier omvandlar kväveföreningar."),
      ("fa", "Fosfor bildar flingor som sjunker", "Fällningskemikalien ger en olöslig fällning."),
      ("fa", "Järnsalt tillsätts vattnet", "Järnsalt är fällningskemikalien.")]),
]
