# -*- coding: utf-8 -*-
"""Instuderingsfrågor och övningsprov för Separationsprocesser."""

def Q(q, a, lines=None, draw=None, note=None):
    d = {"q": q, "a": a}
    if lines: d["lines"] = lines
    if draw: d["draw"] = draw
    if note: d["drawNote"] = note
    return d

INSTUDERING = {"groups": [
 {"title": "Milstolpe 1 – Materiens tre former", "items": [
  Q("Vilka tre former kan materia ha, och vad kallas de tillsammans?",
    "Fast form, flytande form och gas. De kallas ämnets aggregationstillstånd.", 2),
  Q("Rita hur partiklarna ser ut i fast form, flytande form och gas. Använd små kulor.",
    "Fast form: kulorna sitter tätt på bestämda platser (i regelbundna rader). Flytande form: tätt men oordnat, de kan glida förbi varandra. Gas: få kulor med stora avstånd mellan.",
    draw=55, note="Partikelbilden ritar du på papper. Skriv här bara det som ska skrivas, till exempel förklaringen."),
  Q("Hur rör sig partiklarna i fast form, flytande form och gas?",
    "Fast form: de vibrerar på sin plats. Flytande form: de rör sig runt bland varandra men ligger tätt. Gas: de far runt fritt och snabbt med stora avstånd.", 4),
  Q("Varför kan man pressa ihop en gas men knappt en vätska?",
    "I en gas är det stora avstånd mellan partiklarna, så de kan komma närmare varandra. I en vätska ligger partiklarna redan tätt.", 3),
  Q("Vad händer med partiklarnas rörelse när temperaturen höjs?",
    "De rör sig snabbare. Värme är i grunden partiklarnas rörelse.", 2),
  Q("Vad betyder (s), (l) och (g) efter ett ämne i en formel, till exempel H₂O(l)?",
    "(s) står för fast (solid), (l) för flytande (liquid) och (g) för gas. H₂O(l) är flytande vatten.", 2),
 ]},
 {"title": "Milstolpe 2 – Fasövergångar", "items": [
  Q("Vad kallas övergången från fast form till flytande, och från flytande till fast?",
    "Fast till flytande är smältning. Flytande till fast är stelning (eller frysning).", 2),
  Q("Vad är skillnaden mellan avdunstning och kokning?",
    "Vid avdunstning lämnar enstaka partiklar vätskans yta, och det sker vid alla temperaturer. Vid kokning bildas gasbubblor i hela vätskan, och det sker vid kokpunkten.", 4),
  Q("Vad är smältpunkt och kokpunkt? Vilka värden har vatten?",
    "Smältpunkten är temperaturen då ämnet smälter (och stelnar) och kokpunkten temperaturen då vätskan kokar. Vatten: 0 °C och 100 °C vid normalt lufttryck.", 3),
  Q("Etanol har smältpunkten −114 °C och kokpunkten 78 °C. Vilken form har etanol vid 20 °C? Motivera.",
    "Flytande. 20 °C ligger över smältpunkten men under kokpunkten.", 3),
  Q("Varför står temperaturen still när is smälter, trots att man värmer hela tiden?",
    "Energin används till att lösgöra partiklarna från varandra, inte till att öka deras rörelse. Först när all is har smält stiger temperaturen igen.", 4),
  Q("Vad kallas övergången direkt från fast form till gas? Ge ett exempel.",
    "Sublimering. Torris (fast koldioxid) blir koldioxidgas utan att bli flytande.", 2),
  Q("Varför är smältning och kokning fysikaliska förändringar?",
    "Inga nya ämnen bildas. Molekylerna är desamma före och efter, bara rörelsen och avstånden ändras.", 3),
 ]},
 {"title": "Milstolpe 3 – Rena ämnen och blandningar", "items": [
  Q("Vad är ett rent ämne, och vad är en blandning? Ge ett exempel på varje.",
    "Ett rent ämne har bara en sorts partiklar (t.ex. syre eller vatten). En blandning innehåller minst två ämnen som inte har reagerat med varandra (t.ex. luft eller saltvatten).", 4),
  Q("Skilj på homogen och heterogen blandning. Ge ett exempel på varje.",
    "I en homogen blandning ser det likadant ut överallt (saltvatten). I en heterogen blandning kan man urskilja olika delar (sand i vatten).", 3),
  Q("Vilka fyra sorters blandningar tar studieguiden upp? Ge ett exempel på varje.",
    "Lösning (salt i vatten), slamning (lera i vatten), emulsion (mjölk, olja i vatten) och legering (brons).", 4),
  Q("Varför är kranvatten en blandning, även om det är rent nog att dricka?",
    "Det innehåller små mängder lösta salter, kalk och gaser. Rent i vardagsmening är inte samma sak som rent ämne.", 3),
  Q("Vad är densitet, och varför flyter olja på vatten?",
    "Densitet är massa per volym, ρ = m / V. Olja har lägre densitet (ungefär 0,9 g/cm³) än vatten (1,0 g/cm³), så den flyter.", 3),
  Q("Vad är en legering? Ge ett exempel.",
    "En blandning av metaller (eller metall med litet av ett annat grundämne), till exempel brons (koppar och tenn) eller stål (järn och kol).", 2),
 ]},
 {"title": "Milstolpe 4 – Lösningar och löslighet", "items": [
  Q("Förklara begreppen lösningsmedel, löst ämne och lösning med hjälp av saltvatten.",
    "Vattnet är lösningsmedel, saltet är det lösta ämnet och blandningen av dem är lösningen.", 3),
  Q("Du löser 20 g salt i 100 g vatten. Hur mycket väger lösningen? Förklara.",
    "120 g. Saltet har inte försvunnit, det är utspritt i vattnet, så massan bevaras.", 3),
  Q("Skilj på utspädd, koncentrerad och mättad lösning.",
    "Utspädd: lite löst ämne. Koncentrerad: mycket löst ämne. Mättad: lösningen kan inte lösa mer, extra ämne ligger olöst på botten.", 4),
  Q("Hur påverkar temperaturen lösligheten hos fasta ämnen och hos gaser?",
    "De flesta fasta ämnen löser sig bättre i varmt vatten. Gaser löser sig bättre i kallt vatten.", 3),
  Q("Varför kan fiskar få syrebrist i mycket varmt vatten?",
    "Syre är en gas och löser sig sämre i varmt vatten, så det finns mindre syre löst i vattnet.", 3),
  Q("Skilj på hur snabbt något löser sig och hur mycket som kan lösas. Vad påverkar vad?",
    "Omrörning, finfördelning och värme gör att det går snabbare. Hur mycket som kan lösas bestäms av ämnet, lösningsmedlet och temperaturen.", 4),
 ]},
 {"title": "Milstolpe 5 – Att dela upp blandningar med olösta delar", "items": [
  Q("Hur väljer man separationsmetod?",
    "Man utnyttjar en egenskap där ämnena skiljer sig åt: storlek, densitet, magnetism, löslighet eller kokpunkt.", 3),
  Q("Förklara hur sedimentering och dekantering fungerar.",
    "Vid sedimentering får en slamning stå, så att de tätare kornen sjunker och bildar ett sediment. Vid dekantering hälls vätskan försiktigt av så att bottensatsen blir kvar.", 4),
  Q("Rita en uppställning för filtrering och märk ut filterpapper, återstod och filtrat.",
    "Trattan med filterpapper sitter över en bägare. Kornen fastnar på pappret (återstod) och den klara vätskan rinner ned i bägaren (filtrat).",
    draw=60, note="Uppställningen ritar du på papper. Skriv här bara det som ska skrivas."),
  Q("Vilken metod skiljer järnfilspån från sand, och varför fungerar den?",
    "Magnet. Järn är magnetiskt men sand är det inte.", 2),
  Q("Du filtrerar en saltlösning. Vad innehåller filtratet, och varför?",
    "Vatten och löst salt. Det lösta saltet är så litet att det följer med vätskan genom filtret.", 3),
  Q("Hur fungerar en centrifug, och vad används den till?",
    "Blandningen snurras snabbt så att de tyngre delarna pressas utåt och hamnar längst ned. Den används till exempel för att skilja blodkroppar från blodplasma eller grädde från mjölk.", 4),
 ]},
 {"title": "Milstolpe 6 – Att få loss lösta ämnen", "items": [
  Q("Hur kan man få tillbaka saltet ur saltvatten? Vad händer med vattnet?",
    "Med indunstning: vattnet värms så att det förångas och lämnar, och saltet blir kvar som fast ämne. Vattnet går förlorat som ånga.", 4),
  Q("Rita en destillationsuppställning och märk ut kolv, termometer, kylare, kylvatten in och ut samt destillat.",
    "Kolven värms över en låga. Ångan går genom kylaren, där kylvatten går in nedtill och ut upptill, och droppar ned i en bägare som samlar destillatet.",
    draw=70, note="Uppställningen ritar du på papper. Skriv här bara det som ska skrivas."),
  Q("Du destillerar saltvatten. Vad finns i destillatet och vad finns kvar i kolven?",
    "Destillatet är rent vatten (kondenserad vattenånga). Saltet blir kvar i kolven eftersom det inte förångas.", 3),
  Q("Hur kan destillation skilja etanol från vatten?",
    "Etanol har lägre kokpunkt (78 °C) än vatten (100 °C), så ångan blir rikare på etanol. Kyls ångan får man en vätska med mer etanol.", 4),
  Q("Förklara hur papperskromatografi fungerar.",
    "En färgpunkt sitter nära kanten av ett filterpapper som ställs med kanten i vatten. Vattnet vandrar uppåt och tar med färgämnena olika långt, beroende på hur lätt de löser sig och hur hårt de sitter fast, så att blandningen delas i band.", 5),
  Q("Vad är extraktion? Ge ett vardagsexempel.",
    "Att använda ett lösningsmedel för att lösa ut det man vill åt ur en fast blandning. Te- eller kaffebryggning är extraktion: varmt vatten löser ut smakämnena.", 3),
 ]},
 {"title": "Milstolpe 7 – Fällning och analys", "items": [
  Q("Vad är en fällning, och varför är det en kemisk reaktion?",
    "Två klara lösningar blandas och ett nytt, olösligt fast ämne bildas som sjunker. Det är en kemisk reaktion eftersom ett nytt ämne bildas.", 4),
  Q("Vad händer när man blåser koldioxid i kalkvatten, och vad kan man använda det till?",
    "Kalkvattnet blir grumligt vitt eftersom kalciumkarbonat bildas. Det används som test för att påvisa koldioxid.", 3),
  Q("En metallbit väger 54 g och har volymen 20 cm³. Vilken densitet har den, och vilket ämne kan det vara? (Aluminium 2,7 g/cm³, järn 7,9 g/cm³)",
    "ρ = 54 g / 20 cm³ = 2,7 g/cm³. Det är aluminium.", 3),
  Q("Hur kan man ta reda på volymen hos en oregelbunden metallbit?",
    "Man sänker ned den i vatten i en mätcylinder och läser av hur mycket vattennivån stiger. Ökningen är metallbitens volym.", 3),
  Q("Vad visar pH-värdet? Vad betyder pH 7, lägre än 7 och högre än 7?",
    "pH visar hur surt eller basiskt något är. pH 7 är neutralt, lägre än 7 är surt och högre än 7 är basiskt.", 3),
  Q("Nämn ett test för koldioxid, ett för syrgas och ett för stärkelse.",
    "Koldioxid: kalkvatten blir grumligt. Syrgas: en glödande sticka flammar upp. Stärkelse: jodlösning blir blåsvart.", 3),
 ]},
 {"title": "Milstolpe 8 – Separation i samhället", "items": [
  Q("Beskriv stegen i ett reningsverk och vad varje steg tar bort.",
    "Galler (stora föremål), sandfång (sand och grus), försedimentering (slam), biologisk rening (bakterier bryter ned lösta ämnen), kemisk fällning (fosfor fälls ut) och sedimentering eller filter (flingor sjunker eller silas bort).", 6),
  Q("Varför fälls fosfor ut på reningsverket?",
    "Fosfor i utsläpp orsakar övergödning i sjöar och hav. Fällningskemikalien får fosforn att bilda fasta flingor som kan tas bort.", 3),
  Q("Vilka metoder används för att göra dricksvatten av sjövatten?",
    "Till exempel fällning och filtrering (ofta genom sand), och sedan desinfektion med UV-ljus eller klor.", 3),
  Q("Hur kan man få dricksvatten av havsvatten?",
    "Genom destillation eller (vanligare) omvänd osmos, där vattnet pressas genom ett mycket tätt membran som stoppar saltet.", 3),
  Q("Varför är lösta ämnen svårare att rena bort än olösta?",
    "Lösta ämnen är mycket små och följer med vattnet genom galler, sedimentering och filter. Olösta delar kan fångas eller sjunker.", 3),
  Q("Ge två exempel på hur separationsmetoder hjälper återvinningen.",
    "Magneter plockar ut stål, siktar sorterar efter storlek och olika densitet används för att skilja plaster i vattenbad.", 3),
 ]},
 {"title": "Milstolpe 9 – Undersök systematiskt", "items": [
  Q("Vad är en hypotes, och vad ska den uppfylla?",
    "En hypotes är en gissning som bygger på det man redan vet, och den ska gå att pröva genom en undersökning.", 3),
  Q("Skilj på oberoende variabel, beroende variabel och det som hålls konstant.",
    "Den oberoende variabeln ändrar man med avsikt. Den beroende variabeln är det man mäter. Allt annat ska hållas lika (konstant).", 4),
  Q("Varför ska man ändra bara en sak i taget?",
    "Ändrar man flera saker vet man inte vilken som orsakade skillnaden i resultatet.", 3),
  Q("Varför gör man flera försök av samma sort?",
    "För att se hur mycket resultaten varierar och kunna räkna ut ett medelvärde. Ett enda försök kan påverkas av slumpen eller av ett misstag.", 3),
  Q("Vad är en felkälla? Ge två exempel från en filtreringsundersökning.",
    "Något som kan ha gjort resultaten mindre pålitliga. Exempel: man hällde olika snabbt, filtren var olika stora eller en tratt hade hål.", 3),
  Q("Vad krävs för ett välutvecklat svar i en undersökning?",
    "Att man drar generella slutsatser, jämför metoder och värderar resultatens trovärdighet och hur undersökningen kan förbättras, och förklarar med hjälp av begrepp som partiklar och löslighet.", 4),
 ]},
]}

def M(title, left, right, a):
    return {"type": "match", "title": title, "left": left, "right": right, "a": a}

PROV = {"sections": [
 {"title": "Del I – E-nivå (grundläggande)", "questions": [
  M("Para ihop varje fasövergång med rätt beskrivning. Skriv bokstaven i rutan.",
    ["Smältning", "Kokning", "Kondensering", "Stelning", "Sublimering"],
    ["A. Gas blir vätska", "B. Fast form blir gas direkt", "C. Flytande form blir fast", "D. Fast form blir flytande", "E. Vätska blir gas i hela vätskan"],
    "Smältning – D, Kokning – E, Kondensering – A, Stelning – C, Sublimering – B"),
  Q("Vilka tre former kan materia ha? Beskriv hur partiklarna rör sig i var och en.",
    "Fast form: partiklarna vibrerar på sina platser. Flytande form: de rör sig runt bland varandra men ligger tätt. Gas: de far runt fritt med stora avstånd.", 5),
  Q("Rita hur partiklarna i vatten ser ut som is, som flytande vatten och som vattenånga. Använd små kulor.",
    "Is: kulor tätt i regelbundna rader. Flytande vatten: kulor tätt men oordnat. Vattenånga: få kulor med stora avstånd.", 2, draw=55),
  Q("Ett ämne har smältpunkten 5 °C och kokpunkten 120 °C. Vilken form har det vid 20 °C? Motivera.",
    "Flytande. 20 °C ligger över smältpunkten (5 °C) men under kokpunkten (120 °C).", 3),
  Q("Vad är skillnaden mellan ett rent ämne och en blandning? Ge ett exempel på varje.",
    "Ett rent ämne har bara en sorts partiklar (t.ex. syre). En blandning innehåller minst två ämnen som inte reagerat med varandra (t.ex. luft eller saltvatten).", 4),
  Q("Du har salt löst i vatten. Vad är lösningsmedlet, vad är det lösta ämnet och vad är lösningen?",
    "Lösningsmedel: vatten. Löst ämne: salt. Lösning: saltvattnet.", 3),
  Q("Du har en blandning av sand och vatten. Vilken metod kan du använda för att få bort sanden?",
    "Filtrering (sanden blir kvar på filtret), eller sedimentering följt av dekantering.", 3),
  M("Para ihop varje metod med den egenskap den utnyttjar.",
    ["Magnet", "Filtrering", "Destillation", "Sedimentering", "Kromatografi"],
    ["A. Olika kokpunkt", "B. Magnetism", "C. Ämnena vandrar olika snabbt", "D. Storleken på delarna", "E. Olika densitet"],
    "Magnet – B, Filtrering – D, Destillation – A, Sedimentering – E, Kromatografi – C"),
  Q("När is smälter är det fortfarande vatten. Vad kallas en sådan förändring, och varför?",
    "En fysikalisk förändring. Inga nya ämnen bildas, molekylerna är fortfarande H₂O.", 3),
  Q("Nämn två säkerhetsregler när man värmer vätskor vid en laboration.",
    "Till exempel: använd skyddsglasögon, rör aldrig vid het utrustning, värm inte tills allt är torrt, rikta aldrig ett provrör mot någon.", 3),
 ]},
 {"title": "Del II – C-nivå (förklara och tillämpa)", "questions": [
  Q("Förklara varför temperaturen står still när vatten kokar, trots att man värmer hela tiden.",
    "Energin som tillförs används till att lösgöra partiklarna från varandra (vätska blir gas), inte till att öka rörelsen. Temperaturen stiger igen först när allt vatten har kokat.", 4),
  Q("Du löser 15 g salt i 85 g vatten. Hur mycket väger lösningen? Vad blir kvar om du dunstar bort vattnet?",
    "15 g + 85 g = 100 g. Efter indunstning blir 15 g salt kvar.", 3),
  Q("Förklara varför filtrering inte kan ge rent vatten ur saltvatten. Vilken metod fungerar i stället, och hur?",
    "Det lösta saltet är för litet och följer med vätskan genom filtret. Destillation fungerar: vattnet kokar och kondenserar i kylaren medan saltet blir kvar i kolven. (Indunstning ger salt, men vattnet går förlorat.)", 5),
  Q("Rita en destillationsuppställning och märk ut kolv, kylare och destillat.",
    "Kolv över låga, en kylare där kylvatten går in nedtill och ut upptill, och en bägare som samlar destillatet.", 2, draw=70),
  Q("En kolsyrad dryck blir platt fortare i värme. Förklara varför.",
    "Koldioxid är en gas, och gaser löser sig sämre i varm vätska. När drycken är varm kan den inte hålla kvar lika mycket koldioxid, så gasen lämnar vätskan som bubblor.", 4),
  Q("En metallbit väger 27 g och har volymen 10 cm³. Räkna ut densiteten. Är det aluminium (2,7 g/cm³) eller järn (7,9 g/cm³)? Visa hur du räknar.",
    "ρ = m / V = 27 g / 10 cm³ = 2,7 g/cm³. Det är aluminium.", 3),
  Q("Förklara varför en centrifug kan skilja grädde från mjölk.",
    "Blandningen snurras snabbt. De tyngre delarna pressas utåt, medan fettet i grädden har lägre densitet och samlas närmare mitten, så att grädden kan skiljas från skummjölken.", 4),
  Q("Vad händer när man blåser koldioxid i kalkvatten? Varför kallas det en fällning?",
    "Kalkvattnet blir grumligt vitt. Ett nytt, olösligt ämne (kalciumkarbonat) bildas som fast ämne i vätskan, alltså en fällning.", 4),
 ]},
 {"title": "Del III – A-nivå (resonera och dra slutsatser)", "questions": [
  Q("En blandning består av järnspån, sand och salt. Föreslå en plan för att få ut alla tre ämnena var för sig. Motivera varje steg med en egenskap som skiljer ämnena.",
    "1) Magnet drar ut järnspånet (magnetism). 2) Blanda sand och salt med vatten: saltet löser sig (löslighet). 3) Filtrera: sanden blir kvar på filtret. 4) Indunsta filtratet: saltet blir kvar (kokpunkt: vattnet förångas men saltet inte). Ordningen spelar roll: magneten först, filtrering före indunstning.", 8),
  Q("Planera en undersökning som tar reda på vilket av tre filter (kaffefilter, hushållspapper, bomullsvadd) som renar grumligt vatten bäst. Ange frågeställning, hypotes, vad du ändrar, vad du mäter, vad som hålls lika, hur du ökar tillförlitligheten och en möjlig felkälla.",
    "Frågeställning: vilket filter släpper igenom minst grumlighet? Hypotes med motivering (t.ex. tätaste fibrerna). Oberoende variabel: filtertyp. Beroende: hur klart filtratet blir (skala eller avläsning). Konstant: samma blandning och mängd, samma tratt och hällhastighet. Upprepa flera gånger per filter och räkna medelvärde. Felkälla: olika hällhastighet, olika stora filter eller tratt med hål.", 10),
  Q("Ett reningsverk kan ta bort sand och fosfor men inte alla läkemedelsrester. Förklara skillnaden med hjälp av begreppen löst och olöst. Vad skulle behövas för de lösta ämnena?",
    "Sand är olöst och tyngre, så den sjunker eller fångas av galler. Fosfor kan fällas ut till fasta flingor. Många läkemedelsrester är lösta och så små att de följer med vattnet genom filter och bassänger. Man behöver mer avancerade metoder, till exempel filter av kol eller ozonbehandling.", 6),
  Q("Elin påstår: \"Destillation är en kemisk reaktion, eftersom vattnet blir något nytt.\" Bedöm påståendet och motivera.",
    "Påståendet stämmer inte. Vid destillation kokar vattnet till ånga och kondenserar till vatten igen. Ämnet är detsamma, H₂O, bara i en ny form. Ingen ny substans bildas, så det är en fysikalisk förändring.", 5),
  Q("Tiden det tar att lösa 10 g socker i 100 ml vatten: 10 °C: 95 s, 30 °C: 48 s, 50 °C: 25 s, 70 °C: 14 s. Beskriv sambandet, förklara det med partikelmodellen och ge en felkälla samt hur den kan minskas.",
    "Ju högre temperatur, desto kortare tid. Vid högre temperatur rör sig partiklarna snabbare, så vattenmolekylerna och sockerpartiklarna möts oftare och sockret lossnar snabbare. Felkälla: olika omrörning eller att tiden avläses fel. Minskas genom att röra lika, använda samma typ av socker (samma kornstorlek) och samma person som mäter tiden.", 8),
  Q("Havsvatten fryser vid ungefär −1,9 °C men sötvatten vid 0 °C. Förklara varför, och förklara hur det hänger ihop med att man saltar vägar på vintern.",
    "Löst salt sänker fryspunkten, så saltvatten kräver lägre temperatur för att frysa. När salt sprids på isade vägar bildas saltlösning som fryser vid lägre temperatur, så isen smälter vid några minusgrader. Nackdelen är att salt fräter på bilar och skadar växter.", 6),
 ]},
]}
