# -*- coding: utf-8 -*-
"""Begrepp, begreppskort och checklista för Separationsprocesser. Körs av bygg_data.py."""

# term -> definition (svenska). Ankaret (milstolpen där begreppet först förekommer i löptexten) sätts automatiskt.
BEGREPP = {
"Aggregationstillstånd": "Den form ett ämne har: fast, flytande eller gas. Samma ämne kan finnas i alla tre formerna, beroende på temperaturen.",
"Partikelmodellen": "En modell där ämnen ritas som små kulor, partiklar. Partiklarna är alltid i rörelse, och ju högre temperatur, desto snabbare rör de sig.",
"Plasma": "En fjärde form av materia där gasen är så het att elektroner slitits loss från atomerna. Plasma finns i blixtar, norrsken och i solen.",
"Smältning": "Övergången från fast form till flytande form när ämnet värms upp, till exempel när is blir vatten.",
"Stelning": "Övergången från flytande form till fast form när ämnet kyls, till exempel när vatten fryser till is.",
"Smältpunkt": "Den temperatur då ett rent ämne smälter (och stelnar). För vatten är den 0 °C.",
"Avdunstning": "När partiklar lämnar ytan på en vätska och blir gas. Det sker vid alla temperaturer, men snabbare när det är varmt, torrt och blåsigt.",
"Kokning": "När en vätska blir gas i hela vätskan, så att det bildas bubblor. Det sker vid ämnets kokpunkt.",
"Kokpunkt": "Den temperatur då en vätska kokar. För vatten är den 100 °C vid normalt lufttryck.",
"Kondensering": "Övergången från gas till vätska när gasen kyls, till exempel när vattenånga blir droppar på ett kallt glas.",
"Sublimering": "Övergången direkt från fast form till gas utan att ämnet blir flytande, till exempel när torris blir koldioxidgas.",
"Fysikalisk förändring": "En förändring där inga nya ämnen bildas. Ämnet är detsamma efteråt, bara i en annan form eller blandat med något annat.",
"Rent ämne": "Ett ämne som bara innehåller en sorts partiklar, antingen ett grundämne eller en kemisk förening. Det har bestämda smält- och kokpunkter.",
"Densitet": "Hur mycket massa ämnet har per volym, ρ = m / V, ofta i g/cm³. Ämnen med högre densitet än vätskan sjunker i den.",
"Blandning": "Två eller flera ämnen som ligger tillsammans utan att ha reagerat med varandra. Varje ämne behåller sina egenskaper.",
"Homogen blandning": "En blandning som ser likadan ut överallt, så att man inte kan se de olika delarna, till exempel saltvatten och luft.",
"Heterogen blandning": "En blandning där man kan se att den består av olika delar, till exempel sand i vatten eller granit.",
"Lösning": "En homogen blandning där ett ämne är utspritt som mycket små partiklar i ett annat, till exempel salt i vatten.",
"Slamning": "En blandning där fasta korn svävar i en vätska, till exempel lera i vatten. Kornen sjunker med tiden.",
"Emulsion": "En blandning där små droppar av en vätska svävar i en annan vätska som de inte löser sig i, till exempel olja i vatten eller mjölk.",
"Emulgeringsmedel": "Ett ämne som hindrar en emulsion från att skiljas åt, till exempel äggula i majonnäs.",
"Legering": "En blandning av metaller (eller metall med litet av ett annat grundämne), till exempel brons, mässing och stål.",
"Lösningsmedel": "Ämnet som löser upp något annat i en lösning, till exempel vattnet i saltvatten.",
"Löst ämne": "Ämnet som har blivit upplöst i en lösning, till exempel saltet i saltvatten.",
"Mättad lösning": "En lösning som inte kan lösa mer av ämnet. Tillsätter man mer ligger det olöst på botten.",
"Löslighet": "Hur mycket av ett ämne som går att lösa i ett visst lösningsmedel vid en viss temperatur.",
"Separationsmetod": "Ett sätt att dela upp en blandning i sina delar. Metoden utnyttjar att ämnena skiljer sig åt i någon egenskap.",
"Silning": "Att låta en blandning passera en sil med hål av en viss storlek, så att små delar går igenom och stora blir kvar.",
"Sedimentering": "Att låta en slamning stå stilla så att de tyngre kornen sjunker och samlas på botten.",
"Sediment": "Bottensatsen: de korn som har sjunkit till botten när en slamning fått stå.",
"Dekantering": "Att försiktigt hälla av vätskan från ett sediment så att bottensatsen blir kvar.",
"Filtrering": "Att hälla en blandning genom ett filter med mycket små hål. Vätskan går igenom, de olösta kornen blir kvar.",
"Filtrat": "Vätskan som har passerat genom filtret.",
"Centrifugering": "Att snurra en blandning mycket snabbt så att de tyngre delarna pressas utåt och hamnar längst ned i röret.",
"Indunstning": "Att låta lösningsmedlet avdunsta eller koka bort så att det lösta ämnet blir kvar som fast ämne.",
"Destillation": "Att värma en blandning så att ämnet med lägst kokpunkt blir ånga, som sedan kyls och blir vätska igen i en kylare.",
"Destillat": "Vätskan som samlas upp när ångan har kylts och kondenserat vid en destillation.",
"Extraktion": "Att använda ett lösningsmedel för att lösa ut det man vill åt ur en fast blandning, till exempel smak ur teblad.",
"Kromatografi": "En metod för att skilja och identifiera ämnen i en blandning genom att de vandrar olika snabbt, till exempel på filterpapper.",
"Rf-värde": "Sträckan ett ämne har vandrat delat med sträckan lösningsmedlet har vandrat i kromatografi. Värdet ligger mellan 0 och 1.",
"Fällning": "När två lösningar blandas och ett nytt, olösligt fast ämne bildas som sjunker till botten. Ämnet kallas också fällning.",
"Analys": "Att ta reda på vad ett ämne är eller vad ett prov innehåller (påvisa), och hur mycket det innehåller (mäta).",
"pH-värde": "Ett mått på hur surt eller basiskt något är, på en skala från ungefär 0 till 14. pH 7 är neutralt.",
"Indikator": "Ett ämne som ändrar färg beroende på om lösningen är sur eller basisk, till exempel pH-papper.",
"Reningsverk": "En anläggning som renar avloppsvatten i flera steg, med bland annat galler, sedimentering, bakterier och fällning, innan vattnet släpps ut.",
"Omvänd osmos": "En metod där vatten pressas genom ett mycket tätt membran som stoppar det lösta saltet. Används för att avsalta havsvatten.",
"Hypotes": "En gissning som bygger på det man redan vet och som går att pröva genom en undersökning.",
"Variabel": "Något som kan ändras eller mätas i en undersökning. Den man ändrar är den oberoende variabeln, den man mäter är den beroende, och allt annat ska hållas lika (konstant).",
"Felkälla": "Något som kan ha gjort ett mätresultat mindre pålitligt, till exempel en dålig mätning, olika förutsättningar mellan försök eller ett trasigt redskap.",
}

# Begreppskort (memory): två nivåer, korta definitioner
KORT = {
"1": [
 ("Fast form", "Partiklarna sitter på bestämda platser och vibrerar."),
 ("Flytande form", "Partiklarna ligger tätt men glider förbi varandra."),
 ("Gas", "Partiklarna far runt med stora avstånd."),
 ("Smältning", "Fast form blir flytande."),
 ("Kokning", "Flytande form blir gas i hela vätskan."),
 ("Kondensering", "Gas blir vätska."),
 ("Blandning", "Flera ämnen som ligger tillsammans utan att reagera."),
 ("Lösning", "Ett ämne utspritt som mycket små partiklar i ett annat."),
 ("Lösningsmedel", "Ämnet som löser upp, till exempel vatten."),
 ("Filtrering", "Vätskan går igenom, de olösta kornen blir kvar."),
 ("Sedimentering", "Kornen sjunker och samlas på botten."),
 ("Indunstning", "Vätskan dunstar bort och det lösta ämnet blir kvar."),
],
"2": [
 ("Rent ämne", "Bara en sorts partiklar, med bestämd smält- och kokpunkt."),
 ("Densitet", "Massa per volym, ρ = m / V."),
 ("Mättad lösning", "Lösningen kan inte lösa mer, resten ligger olöst."),
 ("Löslighet", "Hur mycket som går att lösa vid en viss temperatur."),
 ("Emulsion", "Små droppar av en vätska i en annan, till exempel mjölk."),
 ("Legering", "En blandning av metaller, till exempel brons."),
 ("Destillation", "Värma, kyla ångan och samla vätskan som destillat."),
 ("Kromatografi", "Ämnen vandrar olika snabbt på filterpapper."),
 ("Centrifugering", "Snabbt snurrande pressar de tunga delarna utåt."),
 ("Fällning", "Ett nytt olösligt ämne bildas när lösningar blandas."),
 ("pH-värde", "Mått på hur surt eller basiskt något är."),
 ("Variabel", "Något som ändras, mäts eller hålls lika i en undersökning."),
],
}

CHECKLISTA = {
"title": "Checklista – Separationsprocesser",
"subject": "Kemi",
"area": "Separationsprocesser",
"intro": "Checklistan följer studieguidens milstolpar. Bocka av det du känner dig trygg med, ett steg i taget. Fördjupningspunkterna är för den som vill komma längre.",
"sections": [
 {"title": "1. Materiens tre former (M1)", "items": [
  "Jag kan beskriva fast form, flytande form och gas med hjälp av partikelmodellen.",
  "Jag vet att partiklarna alltid rör sig och att de rör sig snabbare när temperaturen är högre.",
  "Jag kan förklara varför en gas kan pressas ihop men en vätska knappt kan det.",
  "Jag kan rita hur partiklarna ser ut i fast form, flytande form och gas.",
  "Fördjupning: Jag vet att det finns en fjärde form, plasma."]},
 {"title": "2. Fasövergångar (M2)", "items": [
  "Jag kan namnet på övergångarna: smältning, stelning, avdunstning, kokning, kondensering och sublimering.",
  "Jag vet vad smältpunkt och kokpunkt är och kan avgöra vilken form ett ämne har vid en viss temperatur.",
  "Jag kan förklara varför temperaturen står stilla under smältning och kokning.",
  "Jag vet att en fysikalisk förändring inte bildar några nya ämnen.",
  "Fördjupning: Jag vet vad kelvinskalan och den absoluta nollpunkten är."]},
 {"title": "3. Rena ämnen och blandningar (M3)", "items": [
  "Jag kan skilja på ett rent ämne och en blandning och ge exempel på båda.",
  "Jag kan skilja på homogen och heterogen blandning.",
  "Jag kan namnge och ge exempel på lösning, slamning, emulsion och legering.",
  "Jag vet att ämnena i en blandning behåller sina egenskaper och kan delas utan kemisk reaktion.",
  "Jag vet vad densitet är och kan förklara varför olja flyter på vatten."]},
 {"title": "4. Lösningar och löslighet (M4)", "items": [
  "Jag kan förklara vad lösningsmedel, löst ämne och lösning är.",
  "Jag vet att massan är densamma före och efter att något löses.",
  "Jag kan skilja på utspädd, koncentrerad och mättad lösning.",
  "Jag vet hur temperaturen påverkar lösligheten för fasta ämnen och för gaser.",
  "Fördjupning: Jag kan förklara varför saltat vatten fryser vid lägre temperatur."]},
 {"title": "5. Att dela upp blandningar med olösta delar (M5)", "items": [
  "Jag vet att man väljer separationsmetod efter vad som skiljer ämnena åt.",
  "Jag kan förklara hur silning, sedimentering, dekantering, filtrering och centrifugering fungerar.",
  "Jag kan förklara varför en magnet bara drar till sig vissa ämnen.",
  "Jag kan förklara varför filtrering inte skiljer bort löst salt.",
  "Jag kan välja rätt metod för ett givet problem och motivera valet."]},
 {"title": "6. Att få loss lösta ämnen (M6)", "items": [
  "Jag kan förklara hur indunstning fungerar och vad som blir kvar.",
  "Jag kan beskriva en destillationsuppställning och förklara vad som händer i kolven, kylaren och bägaren.",
  "Jag kan förklara varför destillation kan skilja vätskor med olika kokpunkt.",
  "Jag kan förklara hur extraktion och papperskromatografi fungerar.",
  "Fördjupning: Jag kan räkna ut ett Rf-värde och förklara vad det säger."]},
 {"title": "7. Fällning och analys (M7)", "items": [
  "Jag kan förklara vad en fällning är och att ett nytt ämne bildas.",
  "Jag kan räkna ut densiteten med ρ = m / V och använda den för att identifiera ett ämne.",
  "Jag kan ge exempel på enkla tester för koldioxid, syrgas och stärkelse.",
  "Jag vet vad pH-värdet visar och vad pH 7 betyder.",
  "Fördjupning: Jag kan förklara fällning med hjälp av joner."]},
 {"title": "8. Separation i samhället (M8)", "items": [
  "Jag kan beskriva stegen i ett reningsverk och vilken egenskap varje steg utnyttjar.",
  "Jag kan ge exempel på hur separationsmetoder används för dricksvatten, sockertillverkning och återvinning.",
  "Jag kan förklara varför lösta ämnen är svårare att rena bort än olösta.",
  "Fördjupning: Jag vet hur omvänd osmos och destillation av luft fungerar."]},
 {"title": "9. Undersök systematiskt (M9)", "items": [
  "Jag kan formulera en frågeställning och en hypotes som går att pröva.",
  "Jag kan skilja på oberoende variabel, beroende variabel och det som ska hållas lika.",
  "Jag kan planera en rättvis undersökning och förklara varför man gör flera försök.",
  "Jag kan redovisa resultat i en tabell eller ett diagram och dra en slutsats som stöds av mätningarna.",
  "Jag kan diskutera felkällor och hur jag skulle förbättra undersökningen.",
  "Jag kan arbeta säkert i laborationssalen: skyddsglasögon, ordning och hantering av värme och glas."]},
]}
