# -*- coding: utf-8 -*-
"""Laborationer för Separationsprocesser (egen text). Används av bygg_lab.py."""

LABS = [
{
 "id": "lab-1", "title": "Vad löser sig i vatten?", "milstolpe": "M4", "tid": "30–40 min", "niva": "E–C",
 "syfte": "Att undersöka vilka ämnen som löser sig i vatten, och om temperaturen spelar roll, samt att öva på att göra en rättvis jämförelse.",
 "material": ["Fem provrör eller små genomskinliga glas med etikett", "Koksalt, strösocker, sand, matolja och kaffepulver (en tesked av varje)",
              "Kallt kranvatten och varmt vatten (ca 50 °C, från en vattenkokare, hälls upp av läraren)", "Tesked eller omrörare, mätcylinder (10 ml), klocka", "Skyddsglasögon"],
 "risker": ["Bär skyddsglasögon hela tiden.", "Varmt vatten kan skålla. Hantera glasen försiktigt och torka upp spill direkt.",
            "Smaka aldrig på något i laborationen, inte heller sockret eller saltet."],
 "steg": [(None, [
   "Sätt på skyddsglasögonen. Märk fem glas med ämnenas namn.",
   "Mät upp 10 ml <strong>kallt</strong> vatten i varje glas.",
   "Tillsätt en halv tesked av ett ämne i varje glas. Rör om i 30 sekunder och lika mycket i alla glas.",
   "Titta noga. Är ämnet borta (klart eller färgat), grumligt, ligger det kvar på botten, eller flyter det? Skriv i tabellen.",
   "Häll ut och skölj glasen. Upprepa försöket med <strong>varmt</strong> vatten.",
   "Jämför resultaten och fyll i frågorna."])],
 "resultat": {"cols": ["Ämne", "Kallt vatten: syns ämnet kvar?", "Varmt vatten: syns ämnet kvar?", "Blir det en lösning? (ja/nej)"],
              "rows": ["Koksalt", "Socker", "Sand", "Matolja", "Kaffepulver"]},
 "fragor": ["Vilka ämnen bildade en lösning? Hur kan du se det?",
            "Vad var lösningsmedel och vad var löst ämne i de lösningar som bildades?",
            "Vilket ämne påverkades mest av temperaturen? Förklara med partikelmodellen.",
            "Sanden och oljan löste sig inte. Vilken sorts blandning bildades i de fallen?",
            "Vilka delar av försöket gjorde du lika för att jämförelsen skulle vara rättvis?"],
 "lararnotis": "Ett tillägg för C-nivå: låt eleverna ta reda på hur mycket salt respektive socker som går att lösa i 10 ml vatten genom att tillsätta en nypa i taget tills det ligger kvar (mättad lösning). Man kan lösa cirka 3,5 g salt men cirka 20 g socker i 10 ml vatten vid rumstemperatur.",
},
{
 "id": "lab-2", "title": "Separera en blandning", "milstolpe": "M5–M6", "tid": "60 min", "niva": "C–A",
 "syfte": "Att planera och genomföra en separation av en blandning med fyra ämnen och att kontrollera om ingen massa försvinner.",
 "material": ["Blandning av sand, koksalt, järnfilspån och korkbitar (ca 20 g totalt, väg de olika delarna i förväg)", "Magnet (gärna i en plastpåse)", "Två bägare, tratt och filterpapper, stativ", "Omrörare, vatten, värmetålig skål och värmekälla (kokplatta)", "Våg, skyddsglasögon"],
 "risker": ["Bär skyddsglasögon hela tiden.", "Kokplattan är het även efter avstängning. Rör inte vid skålen. Använd tång.",
            "Avbryt indunstningen när det är lite vätska kvar och låt värmen från skålen göra resten, så sprutar det inte.",
            "Smaka aldrig på saltet."],
 "steg": [("Planera", ["Titta på blandningen och skriv i rutan nedan vilken egenskap som skiljer varje ämne från de andra. Bestäm en ordning för metoderna och motivera den."]),
          ("Genomför", [
   "Väg hela blandningen och skriv ned massan.",
   "Dra ut järnspånet med magneten (lägg magneten i en plastpåse så är det lätt att få loss spånet). Väg järnet.",
   "Häll blandningen i en bägare med ca 100 ml vatten. Rör om. Korkbitarna flyter: sila eller häll av dem. Torka och väg dem.",
   "Filtrera resten. Sanden blir kvar på filtret. Torka sanden och väg den.",
   "Indunsta filtratet i en värmetålig skål. Väg saltet när det är torrt.",
   "Lägg ihop massorna och jämför med den ursprungliga massan."])],
 "resultat": {"cols": ["Del", "Vilken egenskap utnyttjas?", "Massa (g)"],
              "rows": ["Järnspån", "Korkbitar", "Sand", "Salt", "Summa (ska bli lika med startmassan)", "Startmassa"]},
 "fragor": ["Varför måste ordningen vara just den du valde? Vad skulle hända om du indunstade först?",
            "Hur stor skillnad var det mellan startmassan och summan av delarna? Ge två möjliga felkällor.",
            "Är någon av metoderna en kemisk reaktion? Motivera.",
            "Hur skulle du få ut sanden om det i stället var mycket små lerkorn (som inte fastnar lätt)?"],
 "lararnotis": "Blanda ut blandningen i förväg och väg ingående delar för facit. Ett vanligt fel är att elever försöker filtrera innan de har löst saltet. Låt dem prova och diskutera vad som hände i stället för att rätta direkt.",
},
{
 "id": "lab-3", "title": "Kromatografi med tusch", "milstolpe": "M6", "tid": "40 min", "niva": "E–C",
 "syfte": "Att skilja färgämnena i vattenlösliga pennor med papperskromatografi och att beräkna Rf-värden.",
 "material": ["Filterpapper eller kaffefilter (remsor ca 3 × 12 cm)", "Vattenlösliga tuschpennor i olika färger, gärna två svarta av olika märke", "Glas eller bägare, vatten (ca 1 cm djup)", "Blyertspenna och linjal", "Gem eller klädnypa och en penna att hänga remsan på"],
 "risker": ["Använd bara vattenlösliga pennor. Använd inte permanentpennor, som innehåller lösningsmedel.", "Torka upp vatten som spills.", "Skyddsglasögon rekommenderas."],
 "steg": [(None, [
   "Dra en blyertslinje 2 cm från remsans nedre kant. Gör en liten prick av tuschen på linjen. Skriv pennans färg och märke med blyerts högst upp.",
   "Häll 1 cm vatten i glaset. Häng remsan så att nedre kanten når vattnet men <em>pricken är ovanför vattenytan</em>.",
   "Vänta tills vattnet har vandrat nästan upp till toppen (ca 10–15 min). Ta upp remsan och markera med blyerts hur långt vattnet kom.",
   "Låt remsan torka. Rita av hur det ser ut i tabellen.",
   "Mät avståndet från startlinjen till vattenfronten och till mitten av varje färgband. Räkna ut Rf = avstånd färg / avstånd vatten."])],
 "resultat": {"cols": ["Penna", "Färger i bandet", "Avstånd färg (mm)", "Avstånd vatten (mm)", "Rf"],
              "rows": ["Svart, märke 1", "Svart, märke 2", "Blå", "Orange"]},
 "fragor": ["Vilka färger fanns i de svarta pennorna? Var de lika?",
            "Vilket färgämne vandrade längst? Vad säger det om hur det löser sig i vatten?",
            "Varför måste pricken vara ovanför vattenytan i början?",
            "Hur skulle du kunna använda kromatografi för att avgöra vilken penna som skrivit ett hotbrev?"],
 "lararnotis": "Vattenlösliga tuschpennor i olika märken ger stor variation. Testa i förväg. Fungerar även med färgade godisar (lös en bit i en droppe vatten) men de får inte ätas efteråt.",
},
{
 "id": "lab-4", "title": "Destillation av saltvatten", "milstolpe": "M6", "tid": "45 min", "niva": "C–A",
 "syfte": "Att utvinna rent vatten ur saltvatten med destillation och att kontrollera att destillatet är fritt från salt.",
 "material": ["Kolv (t.ex. rundkolv eller Erlenmeyer) med kork och böjt glasrör", "Kylare (eller ett långt rör som kyls av ett hölje med kallt vatten)", "Bägare som samlar destillatet", "Saltvatten (ca 1 msk salt i 100 ml vatten), kokstenar", "Stativ, klämmor, värmekälla", "Två objektglas eller urglas, skyddsglasögon"],
 "risker": ["Bär skyddsglasögon hela tiden. Läraren ska kontrollera uppställningen innan värmen sätts på.",
            "<strong>Uppställningen får aldrig vara helt tillsluten.</strong> Den ska vara öppen i änden där destillatet kommer ut, annars kan trycket spränga glaset.",
            "Kolven, ångan och röret blir mycket heta. Rör inte vid dem. Ånga kan ge brännskador.",
            "Värm aldrig tills kolven är helt torr. Avbryt när ca en tredjedel av vätskan är kvar."],
 "steg": [(None, [
   "Häll 100 ml saltvatten och två kokstenar i kolven (högst halvfull). Ställ upp enligt figuren i studieguiden och kontrollera med läraren.",
   "Anslut kylvattnet: in nedtill, ut upptill.",
   "Värm försiktigt tills vätskan kokar. Skriv ned temperaturen och notera när första dropparna kommer i bägaren.",
   "Samla ca 20 ml destillat. Avbryt värmen när en tredjedel av vätskan är kvar och låt allt svalna.",
   "Lägg en droppe destillat på ett objektglas och en droppe av det ursprungliga saltvattnet på ett annat. Låt dem torka (använd svag värme om det går för långsamt) och jämför vad som blir kvar."])],
 "resultat": {"cols": ["Iakttagelse", "Skriv här"],
              "rows": ["Temperatur när vätskan kokar", "Tid tills första dropparna kommer", "Mängd destillat (ml)", "Kvar efter torkad droppe saltvatten", "Kvar efter torkad droppe destillat"]},
 "fragor": ["Vad händer i kolven, i kylaren och i bägaren? Förklara med partikelmodellen.",
            "Vad blev kvar i kolven och varför?",
            "Vad visar de torkade dropparna om destillatet?",
            "Vilka två fasövergångar ingår? Ange deras namn.",
            "Är destillation en fysikalisk förändring eller en kemisk reaktion? Motivera."],
 "lararnotis": "Kan genomföras som lärardemonstration om kylare saknas: en böjd rörledning i en bägare med isvatten fungerar. Rinnande vatten i kylaren ska gå nedtill uppåt. Smaka aldrig på destillatet i laborationen, men det går bra att mäta med en ledningsförmågemätare om sådan finns.",
},
{
 "id": "lab-5", "title": "Fällning och kalkvatten", "milstolpe": "M7", "tid": "30–40 min", "niva": "C",
 "syfte": "Att iaktta en fällning, påvisa koldioxid med kalkvatten och undersöka hur hårt vatten påverkar tvål.",
 "material": ["Kalkvatten (mättad lösning av kalciumhydroxid) i bägare", "Sugrör (ett per elev), pipetter", "Tvållösning (flytande tvål utspädd med vatten), kranvatten, destillerat vatten", "Fyra provrör med propp, provrörsställ", "Skyddsglasögon"],
 "risker": ["Bär skyddsglasögon hela tiden. Kalkvatten är svagt basiskt och irriterar ögonen. Vid stänk: skölj med mycket vatten och säg till läraren.",
            "<strong>Blås i sugröret, sug aldrig.</strong> Bara en person använder varje sugrör.",
            "Smaka inte på något."],
 "steg": [("Del 1 – koldioxid i kalkvatten", [
   "Häll ca 20 ml kalkvatten i en bägare. Notera hur det ser ut.",
   "Blås försiktigt genom sugröret ned i vattnet i ca en minut. Notera vad som händer.",
   "Låt bägaren stå en stund. Vad händer med det grumliga? Filtrera en del och titta på filtratet."]),
          ("Del 2 – hårt och mjukt vatten", [
   "Fyll två provrör med 10 ml kranvatten och två med 10 ml destillerat vatten.",
   "Tillsätt 5 droppar tvållösning i varje provrör, sätt på proppen och skaka i 10 sekunder.",
   "Jämför skum och grumlighet i kranvatten och destillerat vatten. Skriv i tabellen."])],
 "resultat": {"cols": ["Försök", "Före", "Efter", "Slutsats"],
              "rows": ["Kalkvatten + utandning", "Kranvatten + tvål", "Destillerat vatten + tvål"]},
 "fragor": ["Varför blev kalkvattnet grumligt? Vad kallas det som bildas, och vad är det för ämne?",
            "Vilken gas finns i din utandningsluft som orsakade detta?",
            "Är det en fysikalisk förändring eller en kemisk reaktion? Motivera.",
            "Varför kan man skilja bort fällningen med filtrering, men inte något löst ämne?",
            "Vad fällde tvålen ut i kranvattnet? Hur märktes det på skummet?"],
 "lararnotis": "Kalkvatten görs genom att skaka kalciumhydroxid i destillerat vatten och filtrera bort överskottet. Kalciumhydroxid är irriterande, så bered i dragskåp och hantera med skyddsglasögon. Är kranvattnet mjukt blir skillnaden liten: tillsätt då en droppe kalciumklorid till vattnet, eller använd lite kalkvatten i stället.",
},
{
 "id": "lab-6", "title": "Undersök: vilket filter renar bäst?", "milstolpe": "M9", "tid": "60–80 min", "niva": "C–A",
 "syfte": "Att planera, genomföra och utvärdera en egen undersökning med rättvis jämförelse, upprepade försök och slutsats.",
 "material": ["Grumligt vatten (5 g jord eller lera i 200 ml vatten, omrört)", "Tre sorters filter: kaffefilter, hushållspapper och bomullsvadd", "Tratt (samma för alla), mätcylinder, tre genomskinliga glas", "Ett papper med text eller streck, att titta på genom glaset", "Timer", "Skyddsglasögon"],
 "risker": ["Bär skyddsglasögon. Torka upp spill så ingen halkar.", "Drick aldrig av det filtrerade vattnet.", "Tvätta händerna efter laborationen."],
 "steg": [("Planera (innan du börjar)", [
   "Skriv en frågeställning som går att mäta.",
   "Skriv en hypotes och motivera den.",
   "Fyll i tabellen över variabler: vad ändrar du, vad mäter du, vad håller du lika?",
   "Bestäm hur du mäter hur klart vattnet blir (till exempel en skala 1–5, eller hur väl du ser texten genom glaset). Bestäm hur många försök du gör per filter."]),
          ("Genomför", [
   "Rör om det grumliga vattnet noga före varje försök så att blandningen är lika.",
   "Filtrera 50 ml av det grumliga vattnet genom ett filter. Mät tiden och bedöm klarheten.",
   "Upprepa för alla filter, minst tre gånger per filter. Skriv resultaten direkt i tabellen."]),
          ("Redovisa och värdera", [
   "Räkna ut medelvärden och gör ett stapeldiagram.",
   "Skriv en slutsats som svarar på din fråga och förklara varför utifrån vad du vet om filtrering.",
   "Diskutera felkällor och hur du skulle förbättra undersökningen."])],
 "planering": True,
 "resultat": {"cols": ["Filter", "Försök 1", "Försök 2", "Försök 3", "Medelvärde"],
              "rows": ["Kaffefilter", "Hushållspapper", "Bomullsvadd"]},
 "fragor": ["Svara på din frågeställning. Stödde resultaten din hypotes?",
            "Hur stor var variationen mellan försöken med samma filter? Vad säger det om tillförlitligheten?",
            "Nämn minst två felkällor och hur du skulle minska dem.",
            "Hur kan resultaten förklaras med filtrering och storleken på hålen i filtret?",
            "Vilka resultat skulle bli annorlunda om du filtrerade saltvatten i stället? Motivera."],
 "lararnotis": "Lämpligt för bedömning: hypotes, planering, variabelkontroll, redovisning och värdering (jämför 'Bra svar – tre nivåer' i M9). Låt elever byta planering med en kamrat och testa varandras.",
},
{
 "id": "lab-7", "title": "Värmekurva för is", "milstolpe": "M2", "tid": "45–60 min", "niva": "C",
 "syfte": "Att mäta hur temperaturen förändras när krossad is värms upp, smälter och kokar, och att koppla kurvan till partikelmodellen.",
 "material": ["Bägare (250 ml) med krossad is och lite vatten", "Termometer eller temperatursensor", "Kokplatta eller brännare med stativ", "Omrörare, klocka, millimeterpapper", "Skyddsglasögon"],
 "risker": ["Bär skyddsglasögon hela tiden.", "Kokplattan och bägaren blir heta. Rör inte vid dem och använd tång.", "Rör försiktigt med omrörare, inte med termometern (den kan gå sönder).",
            "Vattnet kan kasta upp droppar när det kokar. Håll ansiktet på avstånd."],
 "steg": [(None, [
   "Fyll bägaren till hälften med krossad is och lite vatten. Rör om och låt termometern visa temperaturen.",
   "Ställ bägaren på kokplattan. Sätt på värmen på svag effekt.",
   "Avläs temperaturen var 30:e sekund och skriv i tabellen. Rör om hela tiden.",
   "Fortsätt tills vattnet har kokat i minst två minuter. Skriv ned vad du ser (is, vatten, bubblor).",
   "Rita en graf med tid på x-axeln och temperatur på y-axeln."])],
 "resultat": {"cols": ["Tid (s)", "Temp (°C)", "Iakttagelse", "Tid (s)", "Temp (°C)", "Iakttagelse"],
              "rows": ["0", "30", "60", "90", "120", "150"]},
 "fragor": ["Vad hände med temperaturen medan isen smälte? Vilken temperatur var det?",
            "Förklara med partikelmodellen varför temperaturen stod still under smältningen.",
            "Vid vilken temperatur kokade vattnet? Stämmer det med värdet i studieguiden?",
            "Vilka fasövergångar ingick i försöket, i ordning?",
            "Varför är det en fysikalisk förändring?"],
 "lararnotis": "Kan även göras med tempsensor och dator för en direkt graf. Kurvan visar tydligt platåerna vid 0 °C och ca 100 °C. Höjden över havet påverkar kokpunkten något.",
},
]
