# -*- coding: utf-8 -*-
"""Begrepp, begreppskort och checklista för Ämnet kemi. Körs av bygg_data.py."""

# term -> definition (svenska). Ankaret (milstolpen där begreppet först förekommer i löptexten) sätts automatiskt.
BEGREPP = {
"Kemi": "Läran om ämnen: vad de består av, vilka egenskaper de har och hur de kan förvandlas till andra ämnen.",
"Materia": "Allt som har massa och tar plats, till exempel fast form, vätska och gas. Allt du kan ta på består av materia.",
"Ämne": "Ett visst slags materia, till exempel vatten, järn, socker eller syre. Ett ämne har bestämda egenskaper.",
"Föremål": "En sak som är gjord av något ämne. En sked är ett föremål, och stålet den är gjord av är ämnet.",
"Kemikalie": "Ett annat ord för ett ämne, särskilt ett som tillverkas eller används i produkter. Vatten och salt är kemikalier.",
"Makronivå": "Den nivå där du ser, känner och mäter, till exempel att vattnet i en bägare har en viss temperatur och massa.",
"Partikelnivå": "Den nivå där du förklarar med atomer, molekyler och joner, som du inte kan se utan bara föreställa dig med en modell.",
"Symbolnivå": "Den nivå där du skriver med kemiska symboler, formler och matematik, till exempel H₂O och ρ = m / V.",
"Naturvetenskaplig metod": "Ett sätt att ta reda på saker: ställa en fråga som går att besvara, gissa med en hypotes, pröva med en rättvis undersökning och dra en slutsats.",
"Frågeställning": "Frågan som en undersökning ska besvara. Den ska gå att besvara med mätningar eller observationer.",
"Hypotes": "En förklarande gissning som går att pröva, ofta skriven som ”Om … så … eftersom …”.",
"Medelvärde": "Summan av alla mätvärden delat med antalet mätvärden. Används för att få ett säkrare resultat när man har upprepat ett försök.",
"Felkälla": "Något som kan ha gjort resultaten mindre säkra, till exempel ojämn mätning eller att något inte hölls lika.",
"Tillförlitlighet": "Hur mycket du kan lita på resultatet. Det blir högre om du upprepar försöket och håller allt utom en sak lika.",
"Variabel": "Något som kan ändras eller mätas i en undersökning.",
"Oberoende variabel": "Det du ändrar med avsikt i en undersökning. Bara en sak ska ändras åt gången.",
"Beroende variabel": "Det du mäter i en undersökning, och som du tror påverkas av det du ändrar.",
"Kontrollvariabel": "En variabel som hålls lika i alla försök, så att jämförelsen blir rättvis.",
"Observation": "Det du faktiskt ser, mäter eller hör. Den skiljer sig från tolkningen av vad det betyder.",
"Teori": "En förklaring som har prövats på många sätt av många forskare och stått emot granskning.",
"Modell": "En förenklad bild som hjälper oss att förstå och förutsäga, till exempel partikelmodellen där ämnen ritas som små kulor.",
"Riskbedömning": "Att tänka igenom innan man börjar: vad kan gå fel, hur allvarligt och troligt är det, och vad kan jag göra för att minska risken.",
"Faropiktogram": "En symbol på en romb med röd kant som visar vilken sorts fara en kemisk produkt har. Det finns nio i EU:s system.",
"Signalord": "Ordet Fara eller Varning på en etikett. Fara används för de allvarligaste farorna och Varning för mindre allvarliga.",
"H-fras": "En faroangivelse på en etikett som beskriver hur produkten är farlig, till exempel H302: Skadligt vid förtäring.",
"P-fras": "En skyddsangivelse på en etikett med råd om säker hantering, till exempel P102: Förvaras oåtkomligt för barn.",
"Bunsenbrännare": "En gasbrännare som används i kemisalen. Med luftringen stängd blir lågan gul, med den öppen blir den blå och hetare.",
"Laborationsrapport": "En text som berättar vad du undersökte, hur du gjorde, vad du fick fram och vad du drar för slutsats, så att någon annan kan upprepa försöket.",
"Egenskap": "Något du kan se, mäta eller pröva hos ett ämne, till exempel färg, densitet och smältpunkt.",
"Fysikalisk egenskap": "En egenskap som du kan iaktta eller mäta utan att ämnet förvandlas till något annat, till exempel färg, densitet och smältpunkt.",
"Kemisk egenskap": "En egenskap som beskriver hur ett ämne reagerar med andra ämnen och bildar nya, till exempel att det brinner eller rostar.",
"Densitet": "Hur mycket massa ämnet har per volym, ρ = m / V, ofta i g/cm³. Ett föremål flyter i en vätska om dess densitet är lägre än vätskans.",
"Alkemi": "En gammal blandning av experiment och filosofi som bland annat försökte göra guld av oädla metaller. Kemin växte fram ur den.",
"Nobelpris": "Ett pris som delas ut varje år, sedan 1901, enligt Alfred Nobels testamente, bland annat i kemi.",
}

KORT = {
"1": [
 ("Kemi", "Läran om ämnen och hur de förändras."),
 ("Ämne", "Ett slags materia, som vatten eller järn."),
 ("Föremål", "En sak som är gjord av ett ämne, som en sked."),
 ("Hypotes", "En förklarande gissning som går att pröva."),
 ("Variabel", "Något som kan ändras eller mätas i en undersökning."),
 ("Oberoende variabel", "Det enda du ändrar med avsikt."),
 ("Beroende variabel", "Det du mäter."),
 ("Faropiktogram", "Symbol på en romb som visar vilken fara ämnet har."),
 ("Signalord", "Fara eller Varning på etiketten."),
 ("Bunsenbrännare", "Gasbrännare med luftring: gul eller blå låga."),
 ("Egenskap", "Något du kan se, mäta eller pröva hos ett ämne."),
 ("Densitet", "Massa per volym, ρ = m / V."),
],
"2": [
 ("Makronivå", "Det du ser och mäter."),
 ("Partikelnivå", "Förklaring med atomer och molekyler."),
 ("Symbolnivå", "Formler, symboler och matematik."),
 ("Naturvetenskaplig metod", "Fråga, hypotes, planera, genomföra, bearbeta, slutsats, värdera."),
 ("Kontrollvariabel", "Hålls lika i alla försök."),
 ("Felkälla", "Något som gör resultatet mindre säkert."),
 ("Tillförlitlighet", "Hur mycket man kan lita på ett resultat."),
 ("Teori", "Förklaring som prövats på många sätt och stått emot granskning."),
 ("Riskbedömning", "Vad kan gå fel, hur troligt, hur minskar jag risken?"),
 ("H-fras", "Faroangivelse, till exempel H302."),
 ("Fysikalisk egenskap", "Kan mätas utan att ämnet förändras."),
 ("Kemisk egenskap", "Beskriver hur ämnet reagerar och bildar nya ämnen."),
],
}

CHECKLISTA = {
"title": "Checklista – Ämnet kemi",
"subject": "Kemi",
"area": "Ämnet kemi",
"intro": "Checklistan följer studieguidens milstolpar. Bocka av det du känner dig trygg med, ett steg i taget. Fördjupningspunkterna är för den som vill komma längre.",
"sections": [
 {"title": "1. Vad är kemi – och varför läsa det? (M1)", "items": [
  "Jag kan förklara vad kemi är och skilja på ämne och föremål.",
  "Jag kan ge exempel på kemi i vardagen, i kroppen och i samhället.",
  "Jag kan förklara vad en kemikalie är och varför ”kemikaliefri” inte finns.",
  "Jag kan ge minst två egna skäl till att läsa kemi.",
  "Fördjupning: Jag kan förklara varför ordet ”kemikaliefritt” i reklam är ett säljargument, inte en kemisk beskrivning."]},
 {"title": "2. Så lär du dig kemi (M2)", "items": [
  "Jag kan förklara vad makronivå, partikelnivå och symbolnivå betyder och ge exempel med vatten.",
  "Jag kan beskriva fyra sätt att lära sig kemi: fakta, samband, räkna och laborera.",
  "Jag vet att man minns bäst genom att testa sig själv och sprida ut träningen över tid.",
  "Jag kan planera hur jag ska öva inför ett prov med hjälp av det.",
  "Fördjupning: Jag kan förklara varför det känns lätt att läsa om, men fungerar sämre."]},
 {"title": "3. Att arbeta naturvetenskapligt (M3)", "items": [
  "Jag kan beskriva de sju stegen: fråga, hypotes, planera, genomföra, bearbeta, slutsats och värdera.",
  "Jag kan skriva en frågeställning som går att besvara med mätningar.",
  "Jag kan skriva en hypotes med förklaring (”Om … så … eftersom …”).",
  "Jag kan skilja på oberoende variabel, beroende variabel och kontrollvariabler i en undersökning.",
  "Jag kan skilja på observation och tolkning, och på hypotes, teori och modell.",
  "Jag kan rita ett diagram med rätt axlar, namn och enheter.",
  "Fördjupning: Jag kan förklara varför man skriver ”stödjer” i stället för ”bevisar”."]},
 {"title": "4. Säkerhet i kemisalen (M4)", "items": [
  "Jag kan mina grundregler: skyddsglasögon, håret uppsatt, inget ätande eller smakande.",
  "Jag vet hur man luktar försiktigt på ett ämne och att man bara gör det om läraren säger det.",
  "Jag kan göra en enkel riskbedömning: vad kan gå fel och hur minskar jag risken?",
  "Jag vet vad jag gör om jag får en kemikalie i ögat, på huden eller får en brännskada.",
  "Jag vet att jag alltid ska säga till läraren direkt om något händer.",
  "Fördjupning: Jag kan förklara skillnaden mellan fara och risk."]},
 {"title": "5. Faropiktogram och etiketter (M5)", "items": [
  "Jag kan känna igen de nio faropiktogrammen och säga vad de betyder.",
  "Jag kan förklara vad signalorden Fara och Varning betyder.",
  "Jag kan förklara vad H-fraser och P-fraser är och ge ett exempel på varje.",
  "Jag kan läsa en etikett och säga vilka faror och vilka skyddsråd som finns.",
  "Fördjupning: Jag vet vad ett säkerhetsdatablad är och vem som ska få det."]},
 {"title": "6. Laboratorieutrustning och att mäta (M6)", "items": [
  "Jag kan namnge vanlig laboratorieutrustning och säga vad den används till.",
  "Jag kan tända, reglera och släcka en bunsenbrännare säkert, och jag vet skillnaden på gul och blå låga.",
  "Jag kan värma ett provrör på ett säkert sätt.",
  "Jag kan avläsa volymen i en mätcylinder vid meniskens nedersta punkt.",
  "Jag vet hur man väger med tarering och hur man använder en termometer.",
  "Fördjupning: Jag kan förklara varför man har ett trådnät på trefoten."]},
 {"title": "7. Laborationsrapporten (M7)", "items": [
  "Jag kan de delar en laborationsrapport har och vad som ska stå i varje del.",
  "Jag kan skilja på vad som hör hemma i resultatdelen och vad som hör hemma i slutsatsen.",
  "Jag kan skriva tal med enhet och göra en tabell med rubriker och enheter.",
  "Jag kan skriva en slutsats som svarar på frågan, förklarar med begrepp och diskuterar felkällor.",
  "Fördjupning: Jag kan förklara varför forskare beskriver sina metoder så noga."]},
 {"title": "8. Ämnens egenskaper (M8)", "items": [
  "Jag kan ge exempel på fysikaliska och kemiska egenskaper.",
  "Jag kan beskriva ett ämne systematiskt: utseende, löslighet, densitet, ledning, magnetism och reaktion.",
  "Jag kan räkna ut densitet med ρ = m / V i tre steg och skriva svaret med enhet.",
  "Jag kan avgöra om ett föremål flyter eller sjunker genom att jämföra densiteter.",
  "Jag kan förklara varför man ofta behöver flera egenskaper för att känna igen ett ämne.",
  "Fördjupning: Jag kan förklara varför ett stålskepp flyter."]},
 {"title": "9. Kemins historia (M9)", "items": [
  "Jag kan berätta om alkemisternas mål och varför kemin växte fram ur alkemin.",
  "Jag kan berätta vad Lavoisier, Berzelius, Dalton och Mendelejev bidrog med.",
  "Jag kan ge exempel på hur Boyles krav på upprepbara försök hänger ihop med laborationsrapporter.",
  "Jag kan ge exempel på hur kemin gav oss nya material, till exempel plast och nylon.",
  "Fördjupning: Jag kan förklara varför Mendelejevs förutsägelser var så viktiga."]},
 {"title": "10. Nobelpris och forskning idag (M10)", "items": [
  "Jag kan berätta vem Alfred Nobel var och vad han bestämde i sitt testamente.",
  "Jag kan ge tre exempel på Nobelpris i kemi som förändrat människors liv.",
  "Jag kan förklara varför ammoniak är viktig för matproduktionen.",
  "Jag kan förklara hur ozonforskningen ledde till åtgärder.",
  "Jag kan ge exempel på vad kemiforskningen arbetar med i dag.",
  "Fördjupning: Jag kan förklara vad metallorganiska nätverk är och vad de kan användas till."]},
]}
