# -*- coding: utf-8 -*-
"""Dra-och-släpp-övningar (sortering) för Kemi som ämne. Ankare på sidan: ov-<id>."""

def act(id, tier, title, intro, zones, items):
    """zones: [(id, text)], items: [(zone, text, why[, hint])]"""
    out = {"id": id, "tier": tier, "title": title, "intro": intro,
           "zones": [{"id": z, "t": t} for z, t in zones], "items": []}
    for i, it in enumerate(items, 1):
        d = {"id": str(i), "zone": it[0], "t": it[1], "why": it[2]}
        if len(it) > 3: d["hint"] = it[3]
        out["items"].append(d)
    return out

SORTERING = [
 act("amne-foremal", "Grund", "Ämne eller föremål?",
     "Ett föremål är en sak. Ett ämne är det den är gjord av. Sortera brickorna.",
     [("a", "Ämne"), ("f", "Föremål")],
     [("f", "Bägare", "En bägare är en sak, ett föremål. Den är gjord av glas."),
      ("a", "Glas", "Glas är ett material, alltså ett ämne."),
      ("f", "Kopparkabel", "Kabeln är en sak. Koppar är ämnet den är gjord av."),
      ("a", "Koppar", "Koppar är ett ämne."),
      ("f", "Provrör", "Ett provrör är en sak, ett föremål."),
      ("a", "Aluminium", "Aluminium är ett ämne (en metall)."),
      ("f", "Spatel", "En spatel är ett redskap, alltså ett föremål."),
      ("a", "Vatten", "Vatten är ett ämne, till skillnad från en vattenflaska."),
      ("f", "Magnet", "En magnet är ett föremål. Den kan vara gjord av järn."),
      ("a", "Järn", "Järn är ett ämne.")]),

 act("nivaer", "Grund", "Makronivå, partikelnivå eller symbolnivå?",
     "Vilken nivå beskriver varje bricka? Du ser och mäter, du föreställer dig partiklar, eller du skriver med symboler.",
     [("ma", "Makronivå (jag ser och mäter)"), ("pa", "Partikelnivå (jag föreställer mig)"), ("sy", "Symbolnivå (jag skriver)")],
     [("ma", "Vattnet i bägaren har temperaturen 20 °C", "Du mäter med en termometer, alltså makronivå."),
      ("ma", "Bitarna av aluminium sjönk i vattnet", "Du ser det direkt, makronivå."),
      ("ma", "Saltet försvann när jag rörde ut det i vattnet", "Du ser vad som händer, utan att förklara. Det är makronivå."),
      ("pa", "Vattenmolekylerna rör sig snabbare när vattnet blir varmare", "Molekyler kan du inte se, du förklarar med en modell: partikelnivå."),
      ("pa", "Saltet delas i laddade partiklar, joner, i vattnet", "Joner är partiklar som du föreställer dig: partikelnivå."),
      ("pa", "Metallatomerna sitter tätt packade i ett regelbundet mönster", "Atomer är partikelnivå."),
      ("sy", "H₂O(l)", "En formel med tillståndsbeteckning: symbolnivå."),
      ("sy", "ρ = m / V", "Formeln för densitet är symbolnivå."),
      ("sy", "Fe", "Järnets kemiska symbol: symbolnivå.")]),

 act("sakerhet", "Grund", "Säkert eller osäkert?",
     "Sortera beteendena. Tänk på vad som kan hända om du gör så.",
     [("s", "Säkert"), ("o", "Osäkert")],
     [("s", "Ta på skyddsglasögon innan du hämtar något", "Ögonen ska vara skyddade hela tiden, från första stund."),
      ("s", "Sätta upp långt hår", "Håret kan annars komma i närheten av lågan."),
      ("s", "Läsa hela instruktionen och etiketterna innan du börjar", "Då vet du vad som ska göras och vilka farorna är."),
      ("s", "Säga till läraren direkt när något spills", "Det är aldrig pinsamt. Läraren vet hur spillet ska hanteras."),
      ("s", "Låta en varm bägare svalna innan du tar i den", "Varm och kall utrustning ser likadan ut."),
      ("s", "Släcka lågan och stänga gaskranen när du är klar", "Lågan ska aldrig lämnas tänd."),
      ("o", "Smaka på ämnet för att se vad det är", "Ät, drick och smaka aldrig i kemisalen. Man kan aldrig veta att något är ofarligt."),
      ("o", "Rikta provröret mot en kompis när du värmer det", "Vätskan kan skvätta ut. Ha aldrig öppningen mot någon."),
      ("o", "Värma en stängd behållare", "Trycket kan spräcka glaset eller sprätta ut proppen."),
      ("o", "Blanda kemikalier på eget initiativ", "Du vet inte vad som kan hända. Gör bara det instruktionen säger."),
      ("o", "Gå ifrån en tänd låga en liten stund", "En tänd låga ska alltid ha någon vid sig."),
      ("o", "Hälla kemikalierester tillbaka i flaskan", "Då kan hela flaskan förorenas. Använd rätt kärl för rester.")]),

 act("olycka", "Grund", "Vad gör du när något händer?",
     "I alla fall säger du direkt till läraren. Vilka olyckor ska du börja skölja på en gång, och när ska du inte röra något själv?",
     [("sk", "Skölj direkt med vatten"), ("ro", "Rör inte själv, säg till läraren")],
     [("sk", "Du får en kemikalie i ögat", "Skölj ögat i minst 15 minuter med ljummet vatten och säg till direkt."),
      ("sk", "Du får en kemikalie på huden", "Skölj direkt med svalt vatten, försiktigt och länge."),
      ("sk", "Du bränner dig på en het bägare", "Spola med svalt vatten, högst 15 minuter. Använd aldrig is."),
      ("ro", "Ett provrör går sönder och skärvor ligger på bänken", "Rör inte skärvorna med händerna. Säg till läraren."),
      ("ro", "En okänd vätska spills på golvet", "Torka inte upp okända kemikalier själv. Säg till läraren."),
      ("ro", "Det börjar brinna på bänken", "Säg till direkt och följ lärarens instruktioner. Läraren stänger gasen och använder brandfilt eller släckare."),
      ("ro", "Någon tror att den har fått i sig något", "Berätta direkt för läraren. Giftinformationscentralen kan kontaktas, och vid livshotande tillstånd ringer man 112.")]),

 act("etikett", "Grund", "Vilken del av etiketten?",
     "På en etikett finns signalord, H-fraser (faroangivelser) och P-fraser (skyddsangivelser). Vad hör till vad?",
     [("si", "Signalord"), ("h", "H-fras (fara)"), ("p", "P-fras (skydd)")],
     [("si", "Fara", "Signalordet Fara används för de allvarligaste farorna."),
      ("si", "Varning", "Signalordet Varning används för mindre allvarliga faror."),
      ("si", "Ordet som visar hur allvarlig faran är", "Det är signalordets uppgift."),
      ("h", "H302: Skadligt vid förtäring", "H står för fara. Den beskriver hur produkten är farlig."),
      ("h", "H319: Orsakar allvarlig ögonirritation", "Det är en faroangivelse: H-fras."),
      ("h", "Beskriver på vilket sätt produkten är farlig", "Det är vad en H-fras gör."),
      ("p", "P102: Förvaras oåtkomligt för barn", "P står för skydd. Det är ett råd om säker hantering."),
      ("p", "Råd om säker hantering", "Det är vad en P-fras är."),
      ("p", "Skyddsangivelse", "Skyddsangivelse är ett annat ord för P-fras.")]),

 act("utrustning", "Grund", "Vilket redskap till vilken uppgift?",
     "Sortera utrustningen efter vad den används till.",
     [("va", "Värma"), ("ho", "Hålla och stödja"), ("bl", "Blanda och förvara"), ("ma", "Mäta och föra över")],
     [("va", "Bunsenbrännare", "Gasbrännare som ger en het låga."),
      ("va", "Trefot", "Bär upp kärlet över lågan."),
      ("va", "Trådnät", "Läggs på trefoten och sprider värmen."),
      ("ho", "Stativ", "En stång på fot som håller övrig utrustning."),
      ("ho", "Muff", "En klämma som fäster en hållare vid stativet."),
      ("ho", "Provrörshållare", "Tång för att hålla ett provrör över lågan."),
      ("ho", "Degeltång", "Tång för heta föremål som en degel eller skål."),
      ("ho", "Provrörsställ", "Ställer provrör upprätt."),
      ("bl", "Bägare", "Används för att blanda, förvara och värma vätskor."),
      ("bl", "Ekolv (erlenmeyerkolv)", "Smal hals så att det inte stänker."),
      ("bl", "Provrör", "Små mängder vid prov."),
      ("bl", "Porslinsskål", "Används till exempel för indunstning."),
      ("ma", "Mätglas (mätcylinder)", "För att mäta volymer."),
      ("ma", "Våg", "För att mäta massa."),
      ("ma", "Termometer", "För att mäta temperatur."),
      ("ma", "Droppipett", "För att föra över små mängder droppvis.")]),

 act("metodsteg", "Grund", "När görs vad i en undersökning?",
     "Sortera stegen efter när de görs: när du planerar, medan du genomför eller när du är klar med försöket.",
     [("pl", "Planera (före)"), ("ge", "Genomföra (under)"), ("ef", "Efter försöket")],
     [("pl", "Formulera frågeställningen", "Utan en frågeställning vet du inte vad du ska undersöka."),
      ("pl", "Skriva en hypotes med ”Om … så … eftersom …”", "Hypotesen skriver du före försöket, innan du vet resultatet."),
      ("pl", "Bestämma vad som ska hållas lika", "Det planerar du innan, så att jämförelsen blir rättvis."),
      ("pl", "Göra en riskbedömning", "Du tänker efter vad som kan gå fel innan du börjar."),
      ("ge", "Mäta och skriva ned med enhet direkt", "Du antecknar det du mäter och ser medan du gör försöket."),
      ("ge", "Upprepa försöket enligt planen", "Att upprepa hör till genomförandet."),
      ("ge", "Följa säkerhetsreglerna", "Säkerheten gäller hela tiden."),
      ("ef", "Räkna ut medelvärdet", "Du bearbetar resultaten när alla mätningar är gjorda."),
      ("ef", "Rita ett diagram", "Diagrammet gör mönstren lättare att se."),
      ("ef", "Dra en slutsats och svara på frågan", "Slutsatsen bygger på resultaten."),
      ("ef", "Fundera över felkällor", "Du värderar efteråt hur säkra resultaten är.")]),

 act("variabler", "Grund", "Oberoende, beroende eller hålls lika?",
     "Tre undersökningar (A, B och C). Vilken sorts variabel är varje bricka?",
     [("ob", "Oberoende (jag ändrar)"), ("be", "Beroende (jag mäter)"), ("ko", "Hålls lika")],
     [("ob", "A: Sorten av papper (hushållspapper, kaffefilter, skrivarpapper)", "A undersöker vilket papper som suger upp mest vatten. Papperet är det du ändrar."),
      ("be", "A: Massan vatten som papperet tagit upp", "Det är vad du mäter."),
      ("ko", "A: Storleken på pappersbitarna och tiden i vattnet", "Det ska vara lika för alla papper."),
      ("ob", "B: Vattnets temperatur (20, 40, 60 °C)", "B undersöker hur snabbt socker löser sig. Temperaturen är det du ändrar."),
      ("be", "B: Tiden tills sockret är borta", "Det är vad du mäter."),
      ("ko", "B: Sockermängden och omrörningen", "Det ska vara lika i alla försök."),
      ("ob", "C: Mängden salt i vattnet", "C undersöker hur saltmängden påverkar hur fort vatten fryser. Saltmängden ändrar du."),
      ("be", "C: Tiden tills vattnet har frusit", "Det är vad du mäter."),
      ("ko", "C: Vattenmängd och kärl", "Det ska vara lika i alla försök.")]),

 act("observation", "Grund", "Observation eller tolkning?",
     "En observation är vad du ser eller mäter. En tolkning är vad du tror att det betyder.",
     [("ob", "Observation"), ("to", "Tolkning")],
     [("ob", "Vattnet blev grumligt när jag blåste i det", "Du såg det, du drar ingen slutsats."),
      ("ob", "Bitarna av aluminium sjönk, korken flöt", "Du iakttog vad som hände."),
      ("ob", "Temperaturen steg från 21 °C till 38 °C", "Du mätte det."),
      ("ob", "Pulvret bubblade när jag tillsatte ättika", "Du såg bubblorna."),
      ("to", "Ett nytt ämne som inte löser sig bildades", "Du drar en slutsats av det du såg."),
      ("to", "Aluminium har högre densitet än vatten", "Du förklarar varför bitarna sjönk. Det är en tolkning."),
      ("to", "Kopp A är bättre isolerad än kopp B", "Du tolkar det du mätte."),
      ("to", "Pulvret måste vara bikarbonat", "Du drar en slutsats, det är en tolkning.")]),

 act("flyter-sjunker", "Grund", "Flyter eller sjunker i vatten?",
     "Vatten har densiteten 1,00 g/cm³. Ett föremål flyter om dess densitet är lägre, och sjunker om den är högre.",
     [("fl", "Flyter"), ("sj", "Sjunker")],
     [("fl", "Olivolja (0,911 g/cm³)", "0,911 är lägre än 1,00, så olivolja flyter."),
      ("fl", "Ett ämne med densiteten 0,85 g/cm³", "0,85 är lägre än 1,00."),
      ("fl", "Ett ämne med densiteten 0,60 g/cm³", "0,60 är lägre än 1,00."),
      ("sj", "Aluminium (2,7 g/cm³)", "2,7 är högre än 1,00."),
      ("sj", "Koppar (8,9 g/cm³)", "8,9 är högre än 1,00."),
      ("sj", "Bly (11,3 g/cm³)", "11,3 är högre än 1,00."),
      ("sj", "Glycerin (1,26 g/cm³)", "1,26 är högre än 1,00, så glycerin sjunker."),
      ("sj", "Ett ämne med densiteten 1,05 g/cm³", "1,05 är högre än 1,00, även om det är nära.")]),

 act("egenskap-typ", "Lär mer", "Fysikalisk eller kemisk egenskap?",
     "En fysikalisk egenskap kan du iaktta eller mäta utan att ämnet blir ett annat. En kemisk egenskap beskriver hur ämnet reagerar och bildar nya ämnen.",
     [("fy", "Fysikalisk egenskap"), ("ke", "Kemisk egenskap")],
     [("fy", "Guld har densiteten 19,3 g/cm³", "Du mäter densiteten, guldet är detsamma efteråt."),
      ("fy", "Koppar leder elektrisk ström", "Koppar är samma ämne när det leder ström."),
      ("fy", "Vatten kokar vid 100 °C", "Vattnet blir gas men är fortfarande H₂O."),
      ("fy", "Socker löser sig i vatten", "Sockret finns kvar i lösningen och kan fås tillbaka."),
      ("fy", "Järn dras till en magnet", "Järnet är detsamma."),
      ("ke", "Järn rostar", "Järnet förvandlas till rost, ett nytt ämne."),
      ("ke", "Ved brinner", "Nya ämnen bildas: koldioxid och vatten."),
      ("ke", "Bikarbonat bubblar när man tillsätter ättika", "En kemisk reaktion, en gas bildas."),
      ("ke", "Mjölk blir sur", "Bakterier bygger om sockret till mjölksyra, alltså nya ämnen.")]),

 act("test-egenskap", "Lär mer", "Vilken egenskap undersöker testet?",
     "Vad ska du ta reda på om du gör så här?",
     [("lo", "Löslighet"), ("le", "Ledningsförmåga"), ("ma", "Magnetism"), ("de", "Densitet")],
     [("lo", "Röra ut lite i vatten och se om det försvinner", "Då undersöker du om ämnet löser sig i vatten."),
      ("lo", "Se om det blir en klar lösning eller ligger kvar på botten", "Det visar löslighet."),
      ("le", "Koppla in batteri och lampa och se om lampan lyser", "Lyser lampan leder ämnet ström."),
      ("le", "Testa om lösningen leder ström", "Det visar om lösta ämnen delas i laddade partiklar."),
      ("ma", "Hålla en magnet intill", "Magnetism testas med en magnet."),
      ("ma", "Se om ämnet dras till en magnet", "Järn, nickel och kobolt dras till en magnet."),
      ("de", "Väga och mäta volymen", "Massa och volym ger densiteten."),
      ("de", "Se om det flyter eller sjunker i vatten", "Det visar om densiteten är lägre eller högre än vattnets."),
      ("de", "Sänka ned det i vatten i en mätcylinder och läsa av nivån", "Så mäter man volymen hos ett oregelbundet föremål, som behövs för densiteten.")]),

 act("historia", "Grund", "Kemins historia i rätt ordning",
     "När hände det? Sortera händelserna efter tidsperiod.",
     [("h1", "Före 1700-talet"), ("h2", "1700-talet"), ("h3", "1800-talet"), ("h4", "1900-talet"), ("h5", "2000-talet")],
     [("h1", "Alkemisterna försöker göra guld av oädla metaller", "Alkemin hör till tiden före 1700-talet."),
      ("h1", "Robert Boyle betonar att experiment ska kunna upprepas", "Boyle verkade på 1600-talet."),
      ("h2", "Lavoisier förklarar förbränning med syre", "Lavoisier verkade på 1700-talet."),
      ("h2", "Scheele upptäcker bland annat syre, klor och mangan", "Scheele verkade på 1700-talet."),
      ("h3", "Dalton gör atomteorin till en prövbar teori (1808)", "Det hände 1808."),
      ("h3", "Berzelius inför bokstavssymboler för grundämnena", "Det hände under 1800-talets början."),
      ("h3", "Mendelejev presenterar det första periodiska systemet (1869)", "Det hände 1869."),
      ("h4", "De första Nobelpriserna delas ut (1901)", "Det hände 1901."),
      ("h4", "Baekeland framställer bakelit, den första helsyntetiska plasten (1907)", "Det hände 1907."),
      ("h4", "De första nylonprodukterna säljs (1939)", "Det hände 1939."),
      ("h5", "Nobelpriset i kemi ges för litiumjonbatterier (2019)", "Det hände 2019."),
      ("h5", "Nobelpriset i kemi ges för genredigering med CRISPR (2020)", "Det hände 2020."),
      ("h5", "Nobelpriset i kemi ges för proteindesign och proteinstrukturer (2024)", "Det hände 2024.")]),
]
