# -*- coding: utf-8 -*-
"""Föremål i labbutrustningsspelet (Kemi som ämne). Egen text; foton av Jesper Tordsson.
Fält: id, namn, ocksa (annat vanligt namn), grupp, lik (id:n som ofta förväxlas), bilder (antal foton),
      fraga (frågan i läget "Vad är det?"; får inte avslöja namnet), anvands (kort, visas efter svar), fakta (rutan "Läs mer")."""

GRUPPER = ["Glas och kärl", "Porslin och värme", "Hålla och stödja", "Mäta och föra över", "Skydd och övrigt"]

FOREMAL = [
 dict(id="bagare", namn="Bägare", grupp=0, lik=["erlenmeyerkolv", "matglas", "glasskal"], bilder=1,
  fraga="Vilket kärl av glas har platt botten, raka sidor och en pip, och används för att blanda, förvara och värma vätskor?",
  anvands="Att blanda, förvara och värma vätskor.",
  fakta="Bägaren har platt botten och en pip som gör det lätt att hälla. Skalan på sidan är bara ungefärlig, så använd ett mätglas när volymen ska vara noggrann. Bägare av värmetåligt glas kan värmas över en låga."),
 dict(id="erlenmeyerkolv", namn="Erlenmeyerkolv", ocksa="ekolv", grupp=0, lik=["bagare", "rundkolv"], bilder=1,
  fraga="Vilken kolv har platt botten och smal hals, så att innehållet inte stänker när du svirlar runt det?",
  anvands="Att blanda och värma vätskor utan att det stänker.",
  fakta="Erlenmeyerkolven kallas ofta ekolv. Den har platt botten och en smal hals, så att du kan svirla runt innehållet utan att det stänker ut. Den passar bra när man blandar eller värmer en vätska."),
 dict(id="rundkolv", namn="Rundkolv", grupp=0, lik=["erlenmeyerkolv", "bagare"], bilder=1,
  fraga="Vilken kolv har rund botten, så att vätskan värms jämnt, till exempel vid destillation?",
  anvands="Att värma vätskor jämnt, till exempel vid destillation.",
  fakta="Rundkolven har en rund botten som värms jämnare än en platt botten. Kolven på bilden har en gummipropp i halsen. Rundkolvar används ofta vid destillation."),
 dict(id="glasskal", namn="Glasskål", grupp=0, lik=["urglas", "bagare"], bilder=1,
  fraga="Vilket öppet, lågt och brett kärl av glas med raka kanter passar när ett ämne ska ligga synligt, till exempel när vatten får dunsta från en lösning?",
  anvands="Att hålla ett ämne öppet och synligt, till exempel vid indunstning.",
  fakta="Glasskålen är ett lågt och brett kärl av glas. Den passar när ett ämne ska ligga öppet och synas väl, till exempel när vatten får dunsta bort från en lösning."),
 dict(id="urglas", namn="Urglas", grupp=0, lik=["glasskal", "bagare"], bilder=1,
  fraga="Vad kallas den böjda, tunna glasskivan som kan läggas som lock över en bägare?",
  anvands="Att täcka en bägare eller hålla en liten mängd ämne.",
  fakta="Urglaset är en böjd glasskiva. Det har fått sitt namn efter formen på glaset på ett gammalt fickur. Du kan använda det som lock på en bägare eller för att hålla en liten mängd av ett ämne."),
 dict(id="provror", namn="Provrör", grupp=0, lik=["provrorsstall", "provrorshallare", "provrorsborste"], bilder=1,
  fraga="Vilket smalt glasrör, stängt i ena änden, används för små mängder vid enkla prov?",
  anvands="Små mängder vid prov och enkla försök.",
  fakta="Provrör är smala glasrör som är stängda i ena änden. Fyll högst en tredjedel av provröret. Bilden visar två olika storlekar."),
 dict(id="tratt", namn="Tratt", grupp=0, lik=["erlenmeyerkolv", "sprutflaska"], bilder=1,
  fraga="Vad använder du tillsammans med filterpapper när du ska filtrera bort ett fast ämne från en vätska?",
  anvands="Att hälla vätska i en trång öppning och att filtrera med filterpapper.",
  fakta="Trattens smala pip gör att vätskan hamnar i kärlet utan att spillas. Sätter du ett filterpapper i tratten kan du filtrera, alltså skilja ett fast ämne från en vätska."),
 dict(id="droppflaska", namn="Droppflaska", grupp=0, lik=["sprutflaska", "pipett"], bilder=1,
  fraga="Vilken flaska har en pipett i korken, så att du kan släppa ut en droppe i taget?",
  anvands="Att förvara en vätska som ska droppas.",
  fakta="Droppflaskan har en pipett i korken, så att du kan släppa ut en droppe i taget. Den är ofta av brunt glas, som skyddar vissa vätskor mot ljus. Etiketten visar vilken kemikalie det är och om den är farlig. På bilden syns faropiktogrammet för brandfarligt."),
 dict(id="sprutflaska", namn="Sprutflaska", grupp=0, lik=["droppflaska", "pipett"], bilder=1,
  fraga="Vilken mjuk plastflaska med böjt rör används ofta med destillerat vatten för att skölja?",
  anvands="Att skölja med, till exempel med destillerat vatten.",
  fakta="När du trycker på den mjuka plastflaskan sprutar vätskan ut genom det böjda röret. Den används ofta med destillerat vatten för att skölja glas eller för att få med de sista resterna av ett ämne."),

 dict(id="bunsenbrannare", namn="Bunsenbrännare", grupp=1, lik=["trefot", "tradnat"], bilder=1,
  fraga="Vilken utrustning ger en het låga och drivs av gas som kommer genom en slang?",
  anvands="Att ge en het låga när något ska värmas.",
  fakta="Bunsenbrännaren drivs av gas som kommer genom slangen. Med luftreglaget ändrar du lågan. Med lite luft blir lågan ljus och sotar, med mer luft blir den hetare och sotar inte. Lämna aldrig en tänd brännare utan uppsikt."),
 dict(id="trefot", namn="Trefot", grupp=1, lik=["tradnat", "porslinstriangel", "stativ"], bilder=1,
  fraga="Vilket ställ av metall med tre ben bär upp kärlet över lågan?",
  anvands="Att bära upp ett kärl över lågan.",
  fakta="Trefoten är ett stabilt ställ av metall med tre ben. Den ställs över bunsenbrännaren och bär upp trådnätet med bägaren eller kolven."),
 dict(id="tradnat", namn="Trådnät", grupp=1, lik=["trefot", "porslinstriangel"], bilder=1,
  fraga="Vad läggs på trefoten för att sprida värmen, så att glaset inte träffas direkt av lågan?",
  anvands="Att sprida värmen så att glaset inte spricker.",
  fakta="Lågan är mycket het på en liten yta. Trådnätet sprider värmen över en större yta, så att glaset inte träffas direkt och spricker. Nätet på bilden har en rund skiva i mitten. Det blir mycket hett och ska svalna innan du rör det."),
 dict(id="porslinstriangel", namn="Porslinstriangel", grupp=1, lik=["trefot", "tradnat", "degel"], bilder=1,
  fraga="Vilken triangelformad hållare, med rör av porslin, bär upp en degel över lågan?",
  anvands="Att stödja en degel över lågan.",
  fakta="Porslinstriangeln har tre porslinsrör som bildar en triangel, hopfogade med metalltråd. Degeln vilar i triangeln medan den värms över lågan. Porslin tål hög värme."),
 dict(id="degel", namn="Degel med lock", grupp=1, lik=["porslinsskepp", "mortel", "smaltskopa"], bilder=1,
  fraga="Vilken liten skål av porslin, med lock, används för att hetta upp fasta ämnen?",
  anvands="Att hetta upp fasta ämnen.",
  fakta="Degeln är en liten skål av porslin med lock. Den tål mycket hög värme. Den vilar i en porslinstriangel när den värms, och du lyfter den med degeltång."),
 dict(id="porslinsskepp", namn="Porslinsskepp", grupp=1, lik=["degel", "smaltskopa"], bilder=1,
  fraga="Vilken avlång, båtformad skål tål hög värme och används för små mängder fast ämne som ska hettas upp?",
  anvands="Att hetta upp små mängder fast ämne.",
  fakta="Porslinsskeppet är en avlång, båtformad skål. Det används när en liten mängd av ett fast ämne ska hettas upp."),
 dict(id="smaltskopa", namn="Smältskopa", grupp=1, lik=["degel", "porslinsskepp"], bilder=1,
  fraga="Vilket långskaftat verktyg, med en liten skål av metall, används för att hetta upp små mängder fast ämne över lågan?",
  anvands="Att hetta upp små mängder fast ämne över lågan.",
  fakta="Smältskopan har en liten metallskål på ett långt skaft med handtag. Med den kan du hålla ett ämne över lågan på avstånd från handen."),
 dict(id="mortel", namn="Mortel med pistill", grupp=1, lik=["degel", "glasskal"], bilder=1,
  fraga="Vad används för att krossa och mala ett fast ämne till pulver?",
  anvands="Att mala fasta ämnen till pulver.",
  fakta="Med pistillen krossar och mal du ämnet mot insidan av mortelns skål. Pulver reagerar ofta snabbare än stora bitar, eftersom det finns mer yta som kan reagera."),

 dict(id="stativ", namn="Stativ", grupp=2, lik=["trefot", "muff", "klamma"], bilder=1,
  fraga="Vad kallas en lodrät stång på en fot, som håller upp och fäster annan utrustning?",
  anvands="Att hålla upp annan utrustning.",
  fakta="Stativet består av en fot och en lodrät stång. Med muffar och klämmor kan du sätta fast kolvar, provrör och annan utrustning på stången."),
 dict(id="muff", namn="Muff", grupp=2, lik=["klamma", "stativ"], bilder=1,
  fraga="Vad används för att fästa en klämma eller hållare vid stativets stång?",
  anvands="Att fästa en klämma vid stativstången.",
  fakta="Muffen har två skruvar. Den ena fäster muffen på stativstången och den andra håller klämman. På så sätt kan klämman flyttas upp och ned och vridas."),
 dict(id="klamma", namn="Klämma", ocksa="hållare", grupp=2, lik=["muff", "degeltang", "provrorshallare"], bilder=1,
  fraga="Vad används för att hålla fast en kolv eller ett provrör på ett stativ?",
  anvands="Att hålla fast en kolv eller ett provrör på stativet.",
  fakta="Klämman fästs på stativstången med en muff. Käftarna håller om till exempel halsen på en kolv. Ofta har käftarna ett skydd av mjukt material, så att glaset inte skadas."),
 dict(id="provrorsstall", namn="Provrörsställ", grupp=2, lik=["provror", "provrorshallare"], bilder=1,
  fraga="Vad gör att provrören står upprätt och inte välter?",
  anvands="Att ställa provrör upprätt.",
  fakta="Provrörsstället gör att provrören står upprätt och inte välter. I ett ställ kan du ha flera prov samtidigt, till exempel när du testar samma ämne med olika vätskor."),
 dict(id="provrorshallare", namn="Provrörshållare", grupp=2, lik=["provror", "provrorsstall", "degeltang"], bilder=1,
  fraga="Vilket hjälpmedel av trä används för att hålla ett provrör över lågan, så att du inte bränner dig?",
  anvands="Att hålla ett provrör över lågan.",
  fakta="Provrörshållaren är ofta av trä, så att den inte blir het. Du klämmer fast provröret och håller det lite snett över lågan, med öppningen bort från alla människor."),
 dict(id="degeltang", namn="Degeltång", grupp=2, lik=["provrorshallare", "klamma"], bilder=1,
  fraga="Vilket verktyg av metall, med långa skänklar, används för att lyfta och flytta en het degel?",
  anvands="Att lyfta och flytta heta föremål, till exempel en degel.",
  fakta="Degeltången är av metall och har långa skänklar. Med den kan du hålla i en het degel eller skål utan att bränna dig. Kom ihåg att ändarna på tången själva blir heta."),

 dict(id="matglas", namn="Mätglas", ocksa="mätcylinder", grupp=3, lik=["bagare", "erlenmeyerkolv"], bilder=1,
  fraga="Vilken smal, hög glascylinder med skala används för att mäta en volym vätska?",
  anvands="Att mäta volymen av en vätska.",
  fakta="Mätglaset kallas också mätcylinder. Det är smalt och högt, med en tydlig skala i milliliter (ml). Läs av skalan med ögonen i höjd med vätskeytan."),
 dict(id="spatel", namn="Spatel", grupp=3, lik=["glasstav", "pipett"], bilder=2,
  fraga="Vad använder du för att ta upp fasta ämnen, till exempel pulver, så att du slipper använda fingrarna?",
  anvands="Att ta upp och föra över fasta ämnen.",
  fakta="Spatlar finns i flera storlekar och former, med platt blad eller en liten sked i änden. Använd en ren spatel för varje ämne, så att ämnena inte blandas. Rör aldrig kemikalier med fingrarna."),
 dict(id="pipett", namn="Pipett", grupp=3, lik=["droppflaska", "glasstav"], bilder=1,
  fraga="Vad använder du för att suga upp och släppa ut små mängder vätska droppvis?",
  anvands="Att föra över små mängder vätska droppvis.",
  fakta="Pipetter finns i plast och i glas. Du trycker ihop gummikupan eller plastkulan, sätter spetsen i vätskan och släpper efter, så sugs vätskan upp. Bilden visar en pipett av plast och en av glas med gummikupa."),

 dict(id="skyddsglasogon", namn="Skyddsglasögon", grupp=4, lik=[], bilder=1,
  fraga="Vad ska du ha på dig hela tiden under en laboration, för att skydda ögonen mot stänk?",
  anvands="Att skydda ögonen mot stänk.",
  fakta="Skyddsglasögon ska du ha på dig under hela laborationen, inte bara vid farliga försök. Har du egna glasögon finns skyddsglasögon som passar utanpå."),
 dict(id="provrorsborste", namn="Provrörsborste", grupp=4, lik=["provror", "provrorsstall"], bilder=1,
  fraga="Vad använder du för att skura rent ett provrör?",
  anvands="Att rengöra provrör och andra smala kärl.",
  fakta="Med borsten och diskmedel kan du skura rent ett provrör. Skölj sedan med vatten, gärna sist med destillerat vatten, så att inga rester stör nästa försök."),
 dict(id="glasstav", namn="Glasstav", grupp=4, lik=["spatel", "pipett"], bilder=1,
  fraga="Vad använder du för att röra om i en vätska, till exempel när ett ämne ska lösas i vatten?",
  anvands="Att röra om i en vätska.",
  fakta="Glasstaven används för att röra om, till exempel när ett ämne ska lösas i vatten. Glas reagerar inte med de flesta ämnen. Med staven kan man också leda vätskan när du häller, så att det inte stänker."),
 dict(id="molekylmodell", namn="Molekylmodell", grupp=4, lik=[], bilder=1,
  fraga="Vad använder man för att visa hur atomerna sitter ihop i en molekyl, med kulor och pinnar?",
  anvands="Att visa hur atomer sitter ihop i en molekyl.",
  fakta="I en molekylmodell är varje atomslag en kula med sin egen färg, och pinnarna visar bindningarna mellan atomerna. Med de vanliga färgerna är svart kol, vitt väte och rött syre."),
 dict(id="spanningskalla", namn="Spänningskälla", grupp=4, lik=[], bilder=1,
  fraga="Vad ger dig en inställbar, ofarlig spänning till försök, till exempel elektrolys, och visar ström och spänning på två mätare?",
  anvands="Att ge ström till försök, till exempel elektrolys.",
  fakta="Spänningskällan ger en lägre och ofarligare spänning än vägguttaget, som du kan ställa in. Instrumenten visar strömstyrka (ampere) och spänning (volt). Den används bland annat vid elektrolys och när man testar om ett ämne leder ström."),
]
