# -*- coding: utf-8 -*-
"""Instuderingsfrågor och övningsprov för Ämnet kemi. Egna uppgifter och egna tal."""

def Q(q, a, lines=None, draw=None, note=None):
    d = {"q": q, "a": a}
    if lines: d["lines"] = lines
    if draw: d["draw"] = draw
    if note: d["drawNote"] = note
    return d

INSTUDERING = {"groups": [
 {"title": "Milstolpe 1 – Vad är kemi och varför ska du läsa det?", "items": [
  Q("Vad är kemi?",
    "Läran om ämnen: vad de består av, vilka egenskaper de har, hur de är uppbyggda av små partiklar och hur ett ämne kan förvandlas till ett annat.", 3),
  Q("Skilj på ämne och föremål med hjälp av ett eget exempel.",
    "Ett föremål är en sak och ett ämne är det den är gjord av. En kopparkabel är ett föremål och koppar är ämnet. Även en gaffel (föremål) av rostfritt stål (ämne) fungerar.", 3),
  Q("Vad är en kemikalie? Är vatten en kemikalie?",
    "En kemikalie är ett annat ord för ett ämne. Ja, vatten är en kemikalie, precis som salt, socker och syre.", 2),
  Q("En tvål säljs som ”helt kemikaliefri”. Vad är fel med påståendet?",
    "Allt består av ämnen, alltså kemikalier, även tvålen och vattnet i den. Med ”kemikaliefri” menar man oftast att vissa ämnen inte ingår. Det är ett säljargument, inte en kemisk beskrivning.", 3),
  Q("Förklara med kemi vad som händer när en cykel rostar.",
    "Järn reagerar med syre och vatten och bildar rost. Rost är ett nytt ämne med helt andra egenskaper än järn.", 3),
  Q("Ge två skäl till att det är bra att kunna kemi, även om du inte blir kemist.",
    "Till exempel: för att förstå vardagen och kroppen, för att kunna fatta kloka beslut och värdera påståenden, för att stora problem som energi och rent vatten kräver kemi, och för att många yrken bygger på det.", 3),
 ]},
 {"title": "Milstolpe 2 – Så lär du dig kemi", "items": [
  Q("Vilka tre nivåer växlar man mellan i kemin? Förklara var och en.",
    "Makronivå: det du ser, känner och mäter. Partikelnivå: du förklarar med atomer och molekyler som du föreställer dig. Symbolnivå: du skriver med symboler, formler och matematik.", 4),
  Q("Vilken nivå är det när du skriver H₂O(l) och vilken nivå är det när du mäter vattnets temperatur?",
    "H₂O(l) är symbolnivå. Att mäta temperaturen är makronivå.", 2),
  Q("Ge ett eget exempel på en kunskap i kemi som du lär dig genom fakta, och ett som du lär dig genom att räkna.",
    "Fakta: vad ett faropiktogram betyder eller vad en utrustning heter. Räkna: att beräkna densitet med ρ = m / V.", 3),
  Q("Vilka två studietekniker är särskilt effektiva enligt forskningen, och vilken är mindre effektiv?",
    "Effektiva: att testa dig själv och att sprida ut träningen över flera tillfällen. Mindre effektivt: att läsa om texten eller stryka under.", 3),
  Q("Varför känns det ofta effektivt att läsa om en text, fast det ger sämre minne?",
    "Texten känns bekant, och det är lätt att tro att bekant betyder att man kan det. Att plocka fram kunskapen själv är svårare, men det är det arbetet som stärker minnet.", 3),
  Q("Planera hur du skulle läsa inför ett prov i kemi under en vecka, så att du använder de effektiva teknikerna.",
    "Ett bra svar delar upp pluggandet på flera dagar, börjar varje tillfälle med att testa sig själv (begreppskort, instuderingsfrågor, kontrollfrågor) med svaret dolt, och avslutar med att kontrollera och repetera det som var svårt.", 5),
 ]},
 {"title": "Milstolpe 3 – Att arbeta naturvetenskapligt", "items": [
  Q("Nämn de sju stegen i det naturvetenskapliga arbetssättet i rätt ordning.",
    "1 Fråga, 2 Hypotes, 3 Planera, 4 Genomför, 5 Bearbeta, 6 Slutsats, 7 Värdera.", 3),
  Q("Vilken av frågorna går att undersöka med mätningar? A: Vilken tvål är bäst? B: Vilken tvål ger mest skum?",
    "B. Det går att mäta hur mycket skum som bildas. ”Bäst” säger inte vad man ska mäta.", 2),
  Q("Skriv en hypotes med formen ”Om … så … eftersom …” om kaffe som svalnar i två olika muggar.",
    "Ett exempel: Om kaffet står i en mugg med lock så svalnar det långsammare, eftersom locket minskar hur mycket värme och ånga som lämnar muggen.", 3),
  Q("Skilj på oberoende variabel, beroende variabel och kontrollvariabel.",
    "Oberoende: det enda du ändrar med avsikt. Beroende: det du mäter. Kontrollvariabler: allt annat, som hålls lika i alla försök.", 4),
  Q("Du undersöker hur mycket vatten tre olika svampar kan ta upp. Ange oberoende och beroende variabel och två kontrollvariabler.",
    "Oberoende: typ av svamp. Beroende: mängden upptaget vatten (massa eller volym). Kontroll: till exempel svampens storlek, hur länge den ligger i vattnet, vattnets temperatur och hur länge den får droppa av.", 4),
  Q("Varför ändrar man bara en variabel i taget, och varför upprepar man försöket?",
    "Ändrar man flera saker vet man inte vilken som orsakade skillnaden. Man upprepar för att se hur mycket resultaten varierar, räkna ett medelvärde och minska risken att slumpen eller ett misstag påverkar.", 4),
  Q("Tre mätvärden är 12,4 s, 12,0 s och 12,8 s. Beräkna medelvärdet.",
    "(12,4 s + 12,0 s + 12,8 s) / 3 = 37,2 s / 3 = 12,4 s. Svar: 12,4 s.", 3),
  Q("Vilka axlar sätter man den oberoende och den beroende variabeln på i ett diagram? Vad ska axlarna ha?",
    "Oberoende på x-axeln och beroende på y-axeln. Båda axlarna ska ha namn och enhet, och en jämn skala.", 3),
  Q("Vilket är en observation och vilket är en tolkning? A: Bitarna av aluminium sjönk. B: Aluminium har högre densitet än vatten.",
    "A är en observation (det du ser). B är en tolkning (vad du drar för slutsats av det).", 2),
  Q("Vad är skillnaden mellan hypotes, teori och modell?",
    "En hypotes är en enskild gissning som ska prövas. En teori är en förklaring som prövats av många och stått emot granskning. En modell är en förenklad bild som hjälper oss att tänka, till exempel partikelmodellen.", 4),
 ]},
 {"title": "Milstolpe 4 – Säkerhet i kemisalen", "items": [
  Q("Vad ska du göra innan du hämtar något i kemisalen, och varför?",
    "Ta på skyddsglasögon och sätta upp håret. Då är ögonen skyddade redan från första stund, och håret kommer inte i närheten av lågan.", 3),
  Q("Varför får man aldrig äta, dricka eller smaka i kemisalen, inte ens på salt eller socker?",
    "Kärl och bänkar kan ha rester av kemikalier, och man kan ta fel ämne. Man kan aldrig veta säkert att något är ofarligt om det har stått i en kemisal.", 3),
  Q("Nämn tre regler för att värma något i ett provrör.",
    "Till exempel: fyll högst en tredjedel, håll med provrörshållare, håll provröret lite snett, rör det försiktigt i lågan, ha aldrig öppningen mot någon, värm aldrig en stängd behållare.", 4),
  Q("Vad menas med en riskbedömning? Vilka tre frågor ställer du?",
    "Att tänka igenom innan man börjar. Vad kan gå fel? Hur allvarligt och hur troligt är det? Vad gör jag för att minska risken?", 4),
  Q("Skilj på fara och risk.",
    "Fara är vad ett ämne kan göra (brandfarligt, frätande, giftigt). Risk är hur troligt det är att något händer och hur illa det då blir. Risken beror på hur mycket, hur länge och hur man hanterar ämnet.", 4),
  Q("Du får en stänk av en kemikalie i ögat. Vad gör du och hur länge?",
    "Säg direkt till läraren och börja skölja ögat med ljummet vatten i minst 15 minuter.", 3),
  Q("Du bränner dig på en het bägare. Vad gör du, och vad ska du inte göra?",
    "Spola med svalt vatten, högst 15 minuter. Använd aldrig is eller snö.", 3),
  Q("Varför är det bra att veta var brandfilt, brandsläckare och ögonspolning finns innan något händer?",
    "Vid en olycka räknas tiden, och då finns det ingen tid att leta.", 2),
 ]},
 {"title": "Milstolpe 5 – Faropiktogram och etiketter", "items": [
  Q("Beskriv hur ett faropiktogram ser ut. Vad är det som berättar vilken fara det är?",
    "En romb (fyrkant på spetsen) med svart symbol på vit botten och röd kant. Det är symbolens form som berättar faran, inte färgen.", 3),
  Q("Hur många faropiktogram finns det i EU:s system? Nämn tre av dem och vad de betyder.",
    "Nio. Till exempel lågan (brandfarligt), dödskallen (akut giftigt) och frätande (fräter på hud och metaller). Utropstecknet betyder att ämnet är skadligt eller irriterande.", 4),
  Q("Vilka uppgifter ska normalt finnas på en etikett på en farlig produkt?",
    "Produktbeteckning, faropiktogram, signalord, H-fraser, P-fraser, leverantörens kontaktuppgifter, mängd (för konsumentprodukter) och UFI-kod.", 5),
  Q("Vad är skillnaden mellan signalorden Fara och Varning?",
    "Fara används för de allvarligaste farorna, Varning för mindre allvarliga.", 2),
  Q("Vad står H och P för i H-fras och P-fras? Ge ett exempel på var och en.",
    "H står för fara (faroangivelse), till exempel H302: Skadligt vid förtäring. P står för skydd (skyddsangivelse), till exempel P102: Förvaras oåtkomligt för barn.", 4),
  Q("Vad är ett säkerhetsdatablad, och vem har rätt att få ett?",
    "Ett dokument med 16 avsnitt om bland annat farliga egenskaper, första hjälpen och hantering. Den som använder kemikalier i sitt arbete, till exempel ett företag, ska få det från leverantören. Privatpersoner har ingen sådan rätt.", 4),
  Q("Varför kan en flaska ha flera faropiktogram?",
    "Ett ämne kan ha flera farliga egenskaper samtidigt, till exempel både vara brandfarligt och irritera ögon.", 3),
 ]},
 {"title": "Milstolpe 6 – Laboratorieutrustning och att mäta", "items": [
  Q("Vilka fyra grupper delas laboratorieutrustningen in i?",
    "Värma, hålla och stödja, blanda och förvara, samt mäta och föra över. (Övrigt: spatel, tratt, filterpapper, magnet.)", 3),
  Q("Vad används trådnät och trefot till?",
    "Trefoten bär upp kärlet över lågan. Trådnätet läggs på trefoten och sprider värmen så att glaset inte träffas av lågan direkt och inte spricker.", 3),
  Q("Skilj på bägare och mätcylinder. När använder du vilken?",
    "En bägare har bara ungefärlig skala och används för att blanda, förvara och värma. En mätcylinder används när volymen ska mätas noggrant.", 3),
  Q("Beskriv i rätt ordning hur du tänder en bunsenbrännare.",
    "Kontrollera slangen, sätt på skyddsglasögon och upp håret. Stäng luftringen. Tänd tändstickan först och håll den vid rörets mynning. Öppna gaskranen sakta.", 5),
  Q("Skilj på den gula och den blå lågan. Vilken är hetast, och vad styr det?",
    "Med luftringen stängd blir lågan gul, sotar och är svalare. Med luftringen öppen blandas gasen med luft, och lågan blir blå, mer koncentrerad och hetast.", 4),
  Q("Rita en mätcylinder med vätska och visa var du läser av volymen.",
    "En cylinder med skala där vätskeytan är böjd. Avläsningen görs vid den nedersta punkten av kurvan (menisken), med ögonen i höjd med ytan.",
    draw=45, note="Bilden ritar du på papper. Skriv här bara det som ska skrivas."),
  Q("Varför ska en termometer hänga fritt i vätskan?",
    "Vilar den mot glasbottnen mäter den glasets temperatur i stället för vätskans.", 2),
 ]},
 {"title": "Milstolpe 7 – Laborationsrapporten", "items": [
  Q("Vilka delar ska en laborationsrapport ha?",
    "Rubrik, syfte och frågeställning, hypotes, material, risker, genomförande, resultat, slutsats och diskussion, och källor.", 5),
  Q("Vad skriver du i resultatdelen och vad skriver du i slutsatsen?",
    "Resultat: det du mätte och såg, med tabeller och diagram, utan förklaringar. Slutsats: svar på frågan, förklaring med kemins begrepp och en värdering av hur säkra resultaten är.", 4),
  Q("Vilken tempus skriver du genomförandet i, och varför?",
    "Dåtid, eftersom det redan är gjort: ”Vi vägde …”.", 2),
  Q("Skriv om meningen så att den blir tydligare: ”Jag hällde i en massa vatten och det blev ganska varmt.”",
    "Ett exempel: ”Jag hällde i 100 ml vatten och temperaturen steg till 38 °C.” Man ska använda mätetal med enhet i stället för ord som ”en massa” och ”ganska”.", 3),
  Q("Varför ska genomförandet skrivas så noga?",
    "Så att någon annan kan upprepa försöket och kontrollera om man får samma resultat.", 3),
  Q("En tabell ska ha vissa delar. Vilka?",
    "Rubrik, kolumnnamn och enheter.", 2),
  Q("Ge två exempel på felkällor du skulle kunna nämna i diskussionen efter en undersökning där du väger vatten.",
    "Till exempel: vågen visade olika värden, du tarerade inte, vatten dunstade under försöket, eller du avläste olika varje gång.", 3),
 ]},
 {"title": "Milstolpe 8 – Ämnens egenskaper", "items": [
  Q("Skilj på fysikalisk och kemisk egenskap. Ge ett exempel på varje.",
    "En fysikalisk egenskap kan du iaktta eller mäta utan att ämnet blir ett annat, till exempel färg eller densitet. En kemisk egenskap beskriver hur ämnet reagerar och då bildar nya ämnen, till exempel att det brinner eller rostar.", 4),
  Q("Nämn fem egenskaper man kan använda för att känna igen ett okänt ämne.",
    "Till exempel utseende, lukt (bara om läraren säger det), löslighet i vatten, densitet, ledningsförmåga, magnetism, smältpunkt, kokpunkt och hur det reagerar.", 3),
  Q("Skriv formeln för densitet och ange en vanlig enhet.",
    "ρ = m / V. Vanlig enhet är g/cm³.", 2),
  Q("En metallbit väger 39,5 g och har volymen 5,0 cm³. Beräkna densiteten. Vilken metall stämmer det med: järn (7,85 g/cm³) eller koppar (8,9 g/cm³)?",
    "ρ = m / V = 39,5 g / 5,0 cm³ = 7,9 g/cm³. Svar: Det stämmer med järn.", 3),
  Q("Hur mycket väger 25 cm³ aluminium? (Densiteten är 2,7 g/cm³)",
    "m = ρ · V = 2,7 g/cm³ · 25 cm³ = 67,5 g. Svar: 67,5 g.", 3),
  Q("Hur kan du mäta volymen hos en oregelbunden sten?",
    "Sänk ned stenen i en mätcylinder med vatten och avläs hur mycket vattennivån stiger. Ökningen är stenens volym.", 3),
  Q("Ett ämne har densiteten 0,85 g/cm³. Flyter eller sjunker det i vatten? Förklara.",
    "Det flyter, eftersom 0,85 g/cm³ är lägre än vattnets 1,00 g/cm³ (om det inte blandar sig med vattnet).", 3),
  Q("Du har två vita pulver: koksalt och bikarbonat. Föreslå ett test som skiljer dem åt och ange vad du ser.",
    "Tillsätt ättika: bikarbonat bubblar, koksalt gör det inte. Löser de sig i vatten hjälper inte testet eftersom båda gör det.", 3),
  Q("Varför är det en fysikalisk egenskap att socker löser sig i vatten?",
    "Sockret finns kvar i lösningen och kan fås tillbaka om vattnet dunstas bort, så inget nytt ämne har bildats.", 3),
 ]},
 {"title": "Milstolpe 9 – Kemins historia", "items": [
  Q("Vad var alkemi, och varför är den viktig i kemins historia?",
    "En blandning av praktiskt arbete, filosofi och vidskepelse där man bland annat försökte göra guld av oädla metaller. Ur allt experimenterande växte kemin fram.", 4),
  Q("Vad bidrog Robert Boyle med?",
    "Han betonade att experiment ska beskrivas noga och kunna upprepas av andra.", 3),
  Q("Vilken slutsats drog Lavoisier om massan i en reaktion, och hur kom han fram till den?",
    "Massan bevaras, alltså den är lika stor före och efter. Han kom fram till det genom att väga noga.", 3),
  Q("Vad bidrog Berzelius, Dalton och Mendelejev med? Para ihop person och bidrag.",
    "Berzelius: bokstavssymboler för grundämnena. Dalton: atomteorin som prövbar teori (1808). Mendelejev: det periodiska systemet (1869) med förutsägelser om okända grundämnen.", 4),
  Q("Vad gjorde Mendelejevs periodiska system särskilt övertygande?",
    "Han lämnade luckor för ämnen som ännu inte var upptäckta och förutsade deras egenskaper. När ämnena upptäcktes stämde egenskaperna ungefär.", 4),
  Q("Vilken var den första helsyntetiska plasten, och vem tillverkade den?",
    "Bakelit, 1907, av Leo Baekeland.", 2),
  Q("Ordna i tidsordning: Dalton, Baekeland, Boyle, Mendelejev, Lavoisier.",
    "Boyle (1600-talet), Lavoisier (1700-talet), Dalton (1808), Mendelejev (1869), Baekeland (1907).", 3),
 ]},
 {"title": "Milstolpe 10 – Nobelpris och forskning idag", "items": [
  Q("Vad bestämde Alfred Nobel i sitt testamente, och när delades de första priserna ut?",
    "Att största delen av hans förmögenhet skulle bilda en fond vars avkastning delas ut som pris. De första priserna delades ut den 10 december 1901.", 3),
  Q("Varför är Fritz Habers upptäckt viktig för maten vi äter?",
    "Ammoniak används till konstgödsel. Växter kan bara ta upp kväve som ingår i kemiska föreningar, och Habers metod gör att kvävet i luften kan användas. Det är en orsak till att en stor del av världens befolkning kan få mat.", 4),
  Q("Vad visade Crutzen, Molina och Rowland, och vad ledde det till?",
    "Att freoner bryter ned ozonlagret. Det ledde till internationella beslut att begränsa sådana ämnen.", 3),
  Q("Vad har Nobelpriset i kemi 2019 betytt för din vardag?",
    "Det gällde litiumjonbatterier, som finns i mobiler, datorer och elbilar och kan lagra energi från förnybara källor.", 3),
  Q("Marie Curie är den första som fått två Nobelpris. I vilka ämnen fick hon dem?",
    "Fysik 1903 och kemi 1911.", 2),
  Q("Kunskap kan användas både till nytta och skada. Ge ett exempel från kapitlet och förklara.",
    "Dynamit underlättade gruvdrift och byggen men kunde också användas som vapen. Freoner var praktiska men skadade ozonlagret. Därför behöver forskare och samhälle tillsammans fundera över hur ny kunskap används.", 4),
  Q("Nämn två frågor som kemiforskningen arbetar med idag.",
    "Till exempel att lagra energi utan utsläpp, rena vatten och fånga koldioxid, utforma nya läkemedel och tillverka och återvinna material hållbart.", 3),
 ]},
]}

def M(title, left, right, a):
    return {"type": "match", "title": title, "left": left, "right": right, "a": a}

PROV = {"sections": [
 {"title": "Del I – E-nivå (grundläggande)", "questions": [
  M("Para ihop varje begrepp med rätt beskrivning. Skriv bokstaven i rutan.",
    ["Ämne", "Föremål", "Kemikalie", "Partikelnivå", "Symbolnivå"],
    ["A. Du förklarar med atomer och molekyler", "B. En sak som är gjord av något ämne", "C. Ett visst slags materia, till exempel järn", "D. Du skriver formler och tecken, till exempel H₂O", "E. Ett annat ord för ett ämne"],
    "Ämne – C, Föremål – B, Kemikalie – E, Partikelnivå – A, Symbolnivå – D"),
  Q("Nämn de sju stegen i det naturvetenskapliga arbetssättet.",
    "Fråga, hypotes, planera, genomför, bearbeta, slutsats, värdera.", 4),
  Q("Du undersöker hur lång tid det tar för is att smälta i vatten av olika temperatur. Ange den oberoende variabeln, den beroende variabeln och två saker som ska hållas lika.",
    "Oberoende: vattnets temperatur. Beroende: tiden tills isen har smält. Lika: isbitens storlek och vattenmängden, samma sorts kärl.", 4),
  Q("Nämn fyra säkerhetsregler i kemisalen.",
    "Till exempel: skyddsglasögon på, håret uppsatt, ät och drick aldrig, läs instruktionen först, säg direkt till läraren om något händer, gå aldrig ifrån en tänd låga.", 4),
  Q("Du får kemikalie i ögat. Vad gör du?",
    "Säg direkt till läraren och skölj ögat med ljummet vatten i minst 15 minuter.", 3),
  M("Para ihop varje del av en etikett med rätt beskrivning.",
    ["Faropiktogram", "Signalord", "H-fras", "P-fras"],
    ["A. Råd om säker hantering", "B. Symbol i en romb med röd kant", "C. Fara eller Varning", "D. Beskriver hur produkten är farlig"],
    "Faropiktogram – B, Signalord – C, H-fras – D, P-fras – A"),
  Q("Vad betyder faropiktogrammet med en låga, och vad betyder faropiktogrammet för frätande?",
    "Låga: brandfarligt. Frätande: fräter på hud och ögon (och på metaller).", 3),
  Q("Skriv formeln för densitet och ange en enhet.",
    "ρ = m / V, med enheten g/cm³.", 2),
  Q("En metallbit väger 108 g och har volymen 40 cm³. Beräkna densiteten. Visa hur du räknar.",
    "ρ = m / V = 108 g / 40 cm³ = 2,7 g/cm³. Svar: 2,7 g/cm³ (stämmer med aluminium).", 3),
  Q("Kärlet du värmer på trefot står på ett trådnät. Vad är trådnätets uppgift?",
    "Det sprider värmen så att glaset inte träffas av lågan direkt och inte spricker.", 3),
  Q("Var på ytan läser du av volymen i en mätcylinder?",
    "Vid den nedersta punkten av den böjda ytan (menisken), med ögonen i höjd med vätskeytan.", 2),
  Q("Vad är skillnaden mellan resultat och slutsats i en laborationsrapport?",
    "Resultat: det du mätte och såg, utan förklaringar. Slutsats: svar på frågan och en förklaring av vad resultatet betyder.", 3),
  Q("Nämn en person i kemins historia och vad personen bidrog med.",
    "Till exempel Lavoisier (massans bevarande, förbränning med syre), Berzelius (bokstavssymboler), Dalton (atomteori) eller Mendelejev (periodiska systemet).", 3),
 ]},
 {"title": "Del II – C-nivå (förklara och tillämpa)", "questions": [
  Q("Förklara hur samma vatten kan beskrivas på makronivå, partikelnivå och symbolnivå.",
    "Makro: du ser och mäter, t.ex. temperatur och volym. Partikel: vattenmolekyler som rör sig. Symbol: H₂O(l).", 4),
  Q("Skriv en hypotes med ”Om … så … eftersom …” till frågan: Löser sig salt fortare i varmt än i kallt vatten?",
    "Exempel: Om vattnet är varmare så löser sig saltet fortare, eftersom partiklarna rör sig snabbare.", 3),
  Q("Du ska undersöka vilken av tre sorters tvål som ger mest skum. Planera undersökningen: fråga, oberoende och beroende variabel, tre saker som hålls lika och hur du gör försöket tillförlitligt.",
    "Fråga: vilken tvål ger mest skum? Oberoende: sorts tvål. Beroende: skummets höjd (mm) eller volym. Lika: vattenmängd, temperatur, samma kärl, samma tid och sätt att skaka. Tillförlitlighet: upprepa varje försök minst tre gånger och räkna medelvärde.", 8),
  Q("Fyra mätningar av tiden det tar för en boll att falla: 1,52 s, 1,48 s, 1,55 s och 1,45 s. Räkna ut medelvärdet. Visa hur du räknar.",
    "(1,52 + 1,48 + 1,55 + 1,45) s / 4 = 6,00 s / 4 = 1,50 s. Svar: 1,50 s.", 3),
  Q("Rita ett diagram av dessa värden och ange vad som ska stå på axlarna: temperatur 10, 30, 50 °C och löslighetstid 80, 40, 20 s.",
    "Temperatur (°C) på x-axeln och tid (s) på y-axeln, med jämn skala. Punkterna (10, 80), (30, 40) och (50, 20) ritas ut. Tiden minskar när temperaturen ökar.", 3, draw=55),
  Q("En metallbit väger 142 g och har volymen 20 cm³. Beräkna densiteten och avgör med tabellen (zink 7,1 g/cm³, tenn 7,3 g/cm³, bly 11,3 g/cm³) vilken metall det kan vara. Visa hur du räknar.",
    "ρ = m / V = 142 g / 20 cm³ = 7,1 g/cm³. Svar: Densiteten är 7,1 g/cm³, vilket stämmer med zink.", 4),
  Q("Hur mycket väger 50 cm³ olivolja? Densiteten är 0,91 g/cm³. Visa hur du räknar.",
    "m = ρ · V = 0,91 g/cm³ · 50 cm³ = 45,5 g. Svar: 45,5 g.", 3),
  Q("Olivolja hälls i vatten. Beskriv vad som händer och förklara med densitet.",
    "Oljan bildar ett lager ovanpå vattnet. Olivolja har lägre densitet (0,91 g/cm³) än vatten (1,00 g/cm³), så den flyter.", 3),
  Q("Förklara skillnaden mellan fara och risk med ett eget exempel.",
    "Fara är vad ämnet kan göra, risk är hur troligt det är att det händer och hur illa det blir. En flaska starkt frätande syra på en hylla har stor fara men liten risk. Om den hälls upp utan glasögon är risken stor.", 4),
  Q("En flaska har piktogrammet med lågan och signalordet Fara. Vad säger det, och vilka åtgärder skulle du vidta när du använder den?",
    "Ämnet är brandfarligt och farligt på ett allvarligt sätt. Håll det borta från lågor, tänd inga brännare i närheten, arbeta i väl ventilerad miljö, använd skyddsglasögon och läs H- och P-fraserna på etiketten.", 5),
  Q("Ge två skäl till att en laborationsrapport ska vara så detaljerad att någon annan kan upprepa försöket.",
    "Man kan kontrollera om man får samma resultat, och man kan hitta fel och förbättra. Att upprepa och granska är en viktig del av vetenskapen.", 4),
  Q("Förklara vilken egenskap som skiljer sockerlösning från saltlösning i ett ledningstest, och varför.",
    "Saltlösningen leder ström, sockerlösningen inte. Lösta salter delas i laddade partiklar (joner) som kan bära strömmen, men socker består av molekyler utan laddning.", 4),
 ]},
 {"title": "Del III – A-nivå (resonera och dra slutsatser)", "questions": [
  Q("Eleverna Maja och Omar jämför hur snabbt två olika sorters te ger färg åt varmt vatten. Maja använder 200 ml kokande vatten och en tepåse av sort A, Omar 150 ml 80-gradigt vatten och en tepåse av sort B. Båda säger att sort A ger mest färg. Bedöm undersökningen: vad är fel, och hur skulle de göra den rättvis? Formulera också en frågeställning och en hypotes.",
    "Undersökningen är inte rättvis eftersom både vattenmängd, temperatur och te ändras (flera variabler). Man vet inte vad som gav skillnaden. Rättvist: samma mängd och temperatur på vattnet, samma kärl, samma tid, ändra bara teet. Frågeställning: Vilken tesort ger mest färg efter 3 minuter? Hypotes: Om teet är finhackat så ger det mer färg, eftersom det har större yta mot vattnet. Upprepa gärna och räkna medelvärde.", 10),
  Q("En elev skriver i sin rapport, under Resultat: ”Sockret löser sig snabbast i det varma vattnet eftersom partiklarna rör sig fortare.” Vad är fel med placeringen, och hur skulle det stå i rätt avsnitt?",
    "Meningen innehåller en förklaring, och den hör hemma i slutsatsen. Resultatdelen ska bara visa vad som hände: ”Sockret var borta efter 11 s i varmt vatten och efter 62 s i kallt vatten.”", 5),
  Q("Ett föremål väger 312 g. Det ser ut som guld men läraren misstänker att det är koppar (8,9 g/cm³) med guldfärg. Föremålets volym mäts genom att sänka det i vatten: nivån stiger från 50 ml till 85 ml. Beräkna densiteten, jämför med guld (19,3 g/cm³) och koppar och dra en slutsats. Vilka felkällor finns?",
    "Volymen är 85 ml − 50 ml = 35 ml = 35 cm³. ρ = m / V = 312 g / 35 cm³ = 8,9 g/cm³. Svar: 8,9 g/cm³, vilket stämmer med koppar (8,9 g/cm³) och inte med guld (19,3 g/cm³). Slutsatsen är att föremålet inte är av rent guld. Felkällor: luftbubblor på föremålet, avläsningsfel vid menisken, vågens noggrannhet. Kanske är föremålet dessutom ihåligt eller belagt, så man kan inte vara helt säker utan fler tester.", 8),
  Q("Ett fartyg är gjort av stål (7,85 g/cm³) men flyter på vatten (1,00 g/cm³). Förklara med begreppet medeldensitet. Vad händer om skrovet får ett hål och fylls med vatten?",
    "Skeppet består av stål och stora hålrum med luft. Skeppets hela massa delat med hela volymen är medeldensiteten, och den är lägre än vattnets, så skeppet flyter. När skrovet fylls med vatten ersätts luften och medeldensiteten ökar. När den blir högre än vattnets sjunker skeppet.", 6),
  Q("En tillverkare hävdar att en produkt är ”helt kemikaliefri och därför säker”. Bedöm påståendet med två argument. Hur kan du ta reda på om produkten kan vara farlig?",
    "Allt består av kemikalier, så påståendet är ett säljargument, inte kemi. Att något är naturligt eller har ett kemiskt namn säger inte om det är farligt. Det viktiga är egenskaperna och hur mycket man utsätts för. Man kan läsa etiketten (piktogram, signalord, H- och P-fraser) och för arbetsbruk säkerhetsdatabladet.", 6),
  Q("Berätta med några exempel hur kemisk forskning har både gjort nytta och orsakat problem, och vilken roll forskning och samhälle har för att hantera det. Använd minst två exempel från kapitlet.",
    "Ett bra svar använder exempel som ammoniak/konstgödsel (mat till fler, men kräver energi och kan ge övergödning), freoner (praktiska men skadade ozonlagret; forskare mätte och varnade, politiker beslutade), plast (många nyttor, men avfallsproblem) eller dynamit (nytta i gruvor och byggen, men kunde användas som vapen). Slutsatsen är att kunskap kan användas på olika sätt, att forskare behöver mäta noga och kommunicera, och att samhället behöver människor som förstår kemi för att kunna fatta kloka beslut.", 10),
  Q("Bedöm påståendet: ”Att en metallbit flyter beror på att den är lätt.” Ge ett motexempel och förklara med rätt begrepp.",
    "Påståendet är fel. Det beror inte på hur tungt föremålet är utan på densiteten (massa per volym). Ett stort träblock är tyngre än en liten spik men flyter, medan spiken sjunker, eftersom trä har lägre densitet än vatten och järn har högre densitet.", 5),
 ]},
]}
