# -*- coding: utf-8 -*-
"""Laborationer för Kemi som ämne (egen text). Används av bygg_lab.py.
Flaggor: planering=True (planeringsruta med variabler), plan_text (egen planeringsruta), graf=("Rubrik", "aria-text")."""

LABS = [
{
 "id": "lab-1", "title": "Bunsenbrännaren: låga och värmning", "milstolpe": "M6", "tid": "40–50 min", "niva": "E–C",
 "syfte": "Att lära dig tända och använda en bunsenbrännare säkert, och att undersöka skillnaden mellan gul och blå låga.",
 "material": ["Bunsenbrännare med gasslang, trefot och trådnät", "Bägare (250 ml) med 100 ml kranvatten, mätcylinder", "Termometer (som hänger fritt i vattnet)", "Tändstickor eller tändare, klocka", "Bägartång, skyddsglasögon"],
 "risker": ["Bär skyddsglasögon hela tiden. Sätt upp långt hår och ha inga lösa kläder.", "Tänd tändstickan <strong>innan</strong> du öppnar gasen. Lämna aldrig en tänd låga.",
            "Håll aldrig handen över lågan. Den blå lågan kan vara svår att se.", "Bägare, trefot och trådnät blir mycket heta. Vänta med att ta i dem och använd tång.",
            "Rör inte om med termometern och låt den inte vila mot glasbottnen."],
 "steg": [("Del 1 – tänd och undersök lågan", [
   "Kontrollera att gasslangen sitter fast och saknar sprickor. Sätt på skyddsglasögonen.",
   "Stäng luftringen. Tänd tändstickan och håll den vid rörets mynning. Öppna gaskranen sakta.",
   "Beskriv den gula lågan i tabellen (färg, höjd, syns den lätt?).",
   "Öppna luftringen tills lågan blir blå. Beskriv den blå lågan.",
   "Stäng luftringen och gaskranen. Låt utrustningen svalna."]),
          ("Del 2 – vilken låga värmer bäst?", [
   "Ställ trefot och trådnät över brännaren. Häll 100 ml kranvatten i bägaren och ställ den på trådnätet. Häng termometern fritt i vattnet och skriv ned starttemperaturen.",
   "Tänd brännaren med <strong>stängd</strong> luftring (gul låga). Värm i exakt 2 minuter. Avläs temperaturen och skriv ned den. Notera om det blev sot på bägaren. Släck och låt svalna.",
   "Byt till nytt kranvatten (100 ml, samma starttemperatur). Tänd brännaren igen och öppna luftringen så att lågan blir blå. Värm i exakt 2 minuter med gaskranen lika mycket öppen som förut. Avläs temperaturen.",
   "Släck lågan, stäng gaskranen och låt allt svalna innan du plockar undan."])],
 "resultat": {"cols": ["Låga", "Starttemp. (°C)", "Sluttemp. efter 2 min (°C)", "Ökning (°C)", "Iakttagelse (färg, sot)"],
              "rows": ["Gul (luftring stängd)", "Blå (luftring öppen)"]},
 "fragor": ["Hur skilde sig den gula och den blå lågan åt i utseende?",
            "Vilken låga värmde vattnet mest? Hur stor var skillnaden?",
            "Vad hölls lika för att jämförelsen skulle bli rättvis? Vad ändrade du?",
            "Vad gör luftringen, och varför blir lågan blå när den öppnas?",
            "Vilka två felkällor kan ha påverkat resultatet, och hur skulle du minska dem?"],
 "lararnotis": "Gör en kort demonstration av tändning först och gå igenom var gasens nödstopp finns. Temperaturökningen beror på gasflöde och bägarens läge, så resultaten varierar mellan grupper, vilket kan användas i en diskussion om tillförlitlighet. Sot på bägarens botten är lätt att torka av när den svalnat.",
},
{
 "id": "lab-2", "title": "Känn igen okända ämnen", "milstolpe": "M8", "tid": "50–60 min", "niva": "C",
 "syfte": "Att använda ämnens egenskaper för att avgöra vilket av tre vita pulver du har, och att öva på att beskriva och dra slutsatser från observationer.",
 "material": ["Tre märkta vita pulver A, B och C (koksalt, strösocker och bikarbonat, i okänd ordning, läraren har facit)", "Tre glas eller provrör, tesked, spatel, förstoringsglas", "Vatten, ättika, pipetter", "Ledningsförmågemätare, eller batteri med lampa, summer eller lysdiod och två elektroder (läraren visar)", "Skyddsglasögon"],
 "risker": ["Bär skyddsglasögon hela tiden.", "<strong>Smaka aldrig</strong> på ämnena, inte heller för att de ser ut som mat.", "Lukta bara om läraren säger det, och då genom att fläkta lite luft mot näsan.",
            "Använd bara batteri för ledningstestet, aldrig nätström.", "Tvätta händerna efter laborationen."],
 "steg": [("Planera", ["Titta på tabellen. Vilka tester tror du kommer att skilja pulvren åt, och vilka hjälper inte? Skriv din plan i rutan ”Din plan” ovanför."]),
          ("Genomför", [
   "Titta på varje pulver med förstoringsglas och beskriv utseendet.",
   "Rör ut en halv tesked av varje pulver i 30 ml vatten i varsitt glas. Beskriv vad du ser (löser det sig helt, blir det grumligt, ligger det kvar?).",
   "Testa om lösningarna leder ström. Skölj elektroderna mellan varje prov.",
   "Ta en ny liten mängd av varje pulver på en tallrik och droppa några droppar ättika på. Beskriv vad som händer.",
   "Fyll i tabellen och avgör vilket pulver som är vilket."])],
 "plan_text": "Vilka tester skiljer pulvren åt? Vilken egenskap tror du att varje test undersöker? Vilka tester tror du inte hjälper?",
 "resultat": {"cols": ["Test", "Pulver A", "Pulver B", "Pulver C"],
              "rows": ["Utseende", "Löser sig i vatten? (ja/nej)", "Lösningen leder ström? (ja/nej)", "Bubblar med ättika? (ja/nej)", "Mitt svar: pulvret är"]},
 "fragor": ["Vilket test skilde inte pulvren åt? Vad lär det dig om hur man väljer test?",
            "Vilket test skilde ut det ena pulvret från de andra två? Vilken egenskap undersöktes?",
            "Vilket av pulvren var koksalt, strösocker och bikarbonat? Motivera med dina resultat.",
            "Vilka observationer i tabellen var det du såg, och vilka delar av ditt svar är tolkningar?",
            "Vilken egenskap som du undersökte är kemisk och vilka är fysikaliska? Motivera."],
 "lararnotis": "Märk pulvren med bokstäver och behåll facit. Förväntat: alla tre löser sig, saltlösningen och bikarbonatlösningen leder ström medan sockerlösningen inte gör det, och bara bikarbonat bubblar med ättika. Med en vanlig glödlampa kan lysningen vara svag eller utebli i lösningarna. Prova ut uppställningen i förväg. En ledningsförmågemätare, en lysdiod med skyddsmotstånd eller en summer fungerar bättre.",
},
{
 "id": "lab-3", "title": "Densitet: vilket ämne är det?", "milstolpe": "M8", "tid": "50–60 min", "niva": "E–C",
 "syfte": "Att mäta massa och volym hos föremål av olika metaller, räkna ut densiteten och avgöra vilket ämne de består av.",
 "material": ["Tre till fem metallföremål av kända ämnen (till exempel aluminium, koppar och järn), både regelbundna (kloss, stav) och oregelbundna (bit, mutter)", "Våg, linjal eller skjutmått", "Mätcylinder med vatten, tråd", "Tabellen över densiteter i studieguidens milstolpe 8", "Räknare, skyddsglasögon"],
 "risker": ["Bär skyddsglasögon.", "Låt metallföremålen glida ned i mätcylindern försiktigt så att glaset inte går sönder.", "Torka upp vatten som spills så ingen halkar.", "Tvätta händerna efter laborationen."],
 "steg": [(None, [
   "Väg varje föremål och skriv ned massan (i g).",
   "Om föremålet är regelbundet, till exempel en kloss: mät längd, bredd och höjd i cm och räkna ut volymen (l · b · h).",
   "Om föremålet är oregelbundet: häll vatten i mätcylindern och avläs volymen. Sänk ned föremålet med en tråd (utan att stänka) och avläs på nytt. Skillnaden är föremålets volym (1 ml = 1 cm³). Avläs vid meniskens nedersta punkt.",
   "Räkna ut densiteten: ρ = m / V. Skriv formeln, sätt in värdena med enheter och skriv svaret med enhet.",
   "Jämför med tabellen i studieguiden och avgör vilket ämne det kan vara.",
   "Pröva om varje föremål flyter eller sjunker i vatten, och jämför med ditt resultat."])],
 "resultat": {"cols": ["Föremål", "Massa (g)", "Volym (cm³)", "Densitet (g/cm³)", "Ämne enligt tabell", "Flyter/sjunker"],
              "rows": ["Föremål 1", "Föremål 2", "Föremål 3", "Föremål 4"]},
 "fragor": ["Visa en av dina uträkningar med formel, insättning med enheter och svar.",
            "Vilka föremål hade lägre respektive högre densitet än vatten? Stämde det med om de flöt?",
            "Vilket ämne bestod varje föremål av? Hur säker är du?",
            "Nämn två felkällor i din mätning av volym eller massa och hur du skulle minska dem.",
            "Kan du vara säker på vilket ämne det är bara utifrån densiteten? Motivera."],
 "lararnotis": "Välj föremål av kända ämnen, och undvik bly och kvicksilver. Många metalldelar är legeringar eller ihåliga, så värdena kan avvika från tabellen. Det är en bra anledning att diskutera felkällor och att densiteten ensam inte alltid räcker. Låt gärna en grupp mäta samma föremål två gånger för att jämföra tillförlitligheten.",
},
{
 "id": "lab-4", "title": "Leder ämnet ström?", "milstolpe": "M8", "tid": "40–50 min", "niva": "E–C",
 "syfte": "Att undersöka vilka fasta ämnen och vilka lösningar som leder elektrisk ström, och att sortera dem efter resultatet.",
 "material": ["Batteri (4,5 V eller lägre), sladdar med krokodilklämmor, lampa, summer eller lysdiod med skyddsmotstånd", "Fasta prov: kopparbit, järnspik, aluminiumfolie, plastbit, glasbit, träbit, blyertsstift", "Lösningar i små glas: destillerat vatten, kranvatten, saltvatten, sockervatten", "Elektroder (två blyertsstift eller metallpinnar), trasa", "Skyddsglasögon"],
 "risker": ["Använd bara batteriet i uppställningen, <strong>aldrig nätström</strong>.", "Bär skyddsglasögon.", "Koppla ifrån batteriet mellan proven. Sladdar och metaller kan bli varma om de kortsluts.",
            "Rör inte vid elektroderna med händerna i lösningarna på längre stunder, och smaka inte på lösningarna.", "Torka upp vatten som spills."],
 "steg": [(None, [
   "Koppla ihop batteri, lampa (eller summer) och två sladdar med fria ändar, så att kretsen är öppen. Testa att den fungerar genom att sätta ihop ändarna en kort stund.",
   "Håll de två fria ändarna mot varsin punkt på ett fast prov. Lyser lampan? Skriv i tabellen.",
   "Testa alla fasta prov. Torka av mellan varje.",
   "Sätt de två elektroderna i en lösning (de får inte vidröra varandra). Lyser lampan eller hörs summern? Skriv i tabellen.",
   "Skölj och torka elektroderna mellan varje lösning. Testa alla fyra lösningarna.",
   "Sortera ämnena i ledare och isolatorer."])],
 "resultat": {"cols": ["Prov", "Lyser/hörs? (ja/nej)", "Leder ström?"],
              "rows": ["Kopparbit", "Järnspik", "Aluminiumfolie", "Plastbit", "Glasbit", "Träbit", "Blyertsstift", "Destillerat vatten", "Kranvatten", "Saltvatten", "Sockervatten"]},
 "fragor": ["Vilka fasta ämnen ledde ström, och vad har de gemensamt?",
            "Vilka lösningar ledde ström? Vad skiljer saltvatten och sockervatten åt?",
            "Vad tror du att det innebär att saltvatten leder ström medan sockervatten inte gör det? (Tips: studieguidens milstolpe 8.)",
            "Varför är metaller lämpliga i elkablar och plast lämplig runt dem?",
            "Vilka felkällor kan göra att ett prov verkar leda dåligt fast det egentligen leder?"],
 "lararnotis": "Med en vanlig glödlampa kan lysningen i saltlösningen vara svag eller utebli. Prova ut uppställningen i förväg. En summer, en lysdiod med skyddsmotstånd eller en ledningsförmågemätare fungerar bättre. Blyertsstift (grafit) leder ström, vilket ofta överraskar. Kranvatten leder ofta något på grund av lösta salter, destillerat vatten leder mycket dåligt.",
},
{
 "id": "lab-5", "title": "Rapportövning: vilket papper suger upp mest vatten?", "milstolpe": "M7", "tid": "60–80 min", "niva": "E–A",
 "syfte": "Att planera, genomföra och redovisa en egen undersökning i en laborationsrapport, med rättvis jämförelse, upprepade försök och värdering.",
 "material": ["Hushållspapper, kaffefilter och skrivarpapper, skurna i kvadrater om 10 × 10 cm (minst tre av varje sort)", "Våg (helst 0,01 g), bägare med vatten, pincett, klocka", "Rapportmallen (skrivs ut från studieguiden) eller eget papper", "Skyddsglasögon"],
 "risker": ["Bär skyddsglasögon.", "Torka upp vatten som spills så ingen halkar.", "Tvätta händerna efter laborationen."],
 "steg": [("Planera (innan du börjar)", [
   "Skriv frågeställningen och en hypotes (”Om … så … eftersom …”).",
   "Fyll i rutan för variabler: vad ändrar du, vad mäter du och vad håller du lika?",
   "Bestäm hur många försök du gör per papper och hur länge papperet ska ligga i vattnet och droppa av."]),
          ("Genomför", [
   "Väg en torr kvadrat och skriv ned massan.",
   "Håll ned kvadraten under vattenytan med pincett lika länge varje gång (till exempel 10 sekunder). Lyft upp och låt den droppa av lika länge varje gång (till exempel 5 sekunder).",
   "Väg den våta kvadraten. Upptaget vatten = massa efter minus massa före. Skriv i tabellen.",
   "Upprepa minst tre gånger för varje papperstyp."]),
          ("Redovisa och värdera", [
   "Räkna ut medelvärde för varje papperstyp.",
   "Skriv en laborationsrapport med alla delar (rubrik, syfte, hypotes, material, risker, genomförande, resultat, slutsats och diskussion).",
   "Byt rapport med en kamrat och kontrollera om den kan upprepa försöket utifrån din text."])],
 "planering": True,
 "resultat": {"cols": ["Papperstyp", "Försök 1 (g)", "Försök 2 (g)", "Försök 3 (g)", "Medelvärde (g)"],
              "rows": ["Hushållspapper", "Kaffefilter", "Skrivarpapper"]},
 "fragor": ["Svara på din frågeställning. Stödde resultaten din hypotes?",
            "Hur mycket varierade resultaten mellan försöken med samma papper, jämfört med skillnaden mellan papperstyperna? Vad säger det om tillförlitligheten?",
            "Nämn minst två felkällor och hur du skulle minska dem.",
            "Förklara resultatet med hjälp av papperets uppbyggnad (fibrer och hålrum).",
            "Vilken ny fråga väcker din undersökning?"],
 "lararnotis": "Studieguiden har en exempelrapport med påhittade mätvärden. Eleverna får egna värden som kan skilja sig. Papper varierar mellan märken, och det gör inget. Lämpligt för bedömning av planering, variabelkontroll, redovisning och värdering. Låt elever byta rapporter och pröva varandras genomförande.",
},
{
 "id": "lab-6", "title": "Ägget i saltvatten: flyta eller sjunka?", "milstolpe": "M8", "tid": "30–40 min", "niva": "E–C",
 "syfte": "Att undersöka hur mängden salt i vatten påverkar om ett ägg flyter eller sjunker, och att förklara det med densitet.",
 "material": ["Ett ägg (rått eller hårdkokt, samma ägg hela tiden)", "Högt glas eller mätcylinder (500 ml) med 250 ml kranvatten", "Koksalt, matsked, omrörare", "Skyddsglasögon, trasa"],
 "risker": ["Bär skyddsglasögon.", "Om du använder rått ägg: tvätta händerna efteråt och släng ägget. Smaka aldrig på ägget eller vattnet.", "Torka upp spill så ingen halkar."],
 "steg": [(None, [
   "Häll 250 ml kranvatten i glaset. Lägg försiktigt ned ägget. Flyter eller sjunker det? Skriv i tabellen.",
   "Lyft upp ägget. Tillsätt en matsked salt och rör tills allt salt har löst sig.",
   "Lägg ned ägget. Flyter, sjunker eller svävar det? Skriv i tabellen.",
   "Upprepa: en matsked salt i taget, rör noga, och lägg ned ägget varje gång, tills ägget flyter.",
   "Fundera: hur kan du få ägget att sväva mitt i vätskan? Prova ditt förslag."])],
 "resultat": {"cols": ["Antal matskedar salt", "Ägget sjunker, svävar eller flyter?"],
              "rows": ["0", "1", "2", "3", "4", "5", "6"]},
 "fragor": ["Vad hände med ägget när du tillsatte salt? Beskriv med det du såg.",
            "Förklara med densitet varför ägget flöt eller sjönk i olika saltlösningar.",
            "Vad ändrade du, vad mätte du och vad höll du lika?",
            "Hur fick du ägget att sväva, och vad betyder det för äggets densitet jämfört med vätskans?",
            "Ägg av olika ålder och storlek kan bete sig olika. Hur påverkar det hur säker din slutsats är?"],
 "lararnotis": "Saltmängden som krävs beror på äggets storlek och ålder, så prova i förväg och gör gärna fler rader i tabellen. Ett sätt att få ägget att sväva är att lägga saltvatten längst ned i glaset och försiktigt hälla färskt vatten ovanpå längs en sked, så att två lager bildas. Är resultatet oväntat är det en bra fråga om felkällor: var saltet helt löst?",
},
]
